### ISSUE TITLE
Oakland, CA

### ISSUE THREAD

**Issue by underpickled** [teddywilson/defund12.org#10]

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

**Comment by underpickled** [comment]
Subject: Now is the time to defund the Oakland Police Department

Officials: Libby Schaaf (officeofthemayor@oaklandnet.com), Dan Kalb (dkalb@oaklandnet.com), Nikki Fortunato Bas (NfortunatoBas@oaklandca.gov), Lynette Gibson McElhaney (lmcelhaney@oaklandnet.com), Sheng Thao (SThao@oaklandca.gov), Noel Gallo (ngallo@oaklandnet.com), Loren Taylor (LTaylor@oaklandca.gov), Larry Reid (lreid@oaklandnet.com)

Message: Incoming

**Comment by cjappl** [comment]
@underpickled If you would like someone to read or review the message in any way I would be more than happy to help!! Don't hesitate to ask. Thanks for everything you're doing :)

**Comment by underpickled** [comment]
@cjappl thank you! I'm reaching out to Anti Police-Terror Project since they've been working on this for some time and might have a better prepared statement. Once I hear from them I'll fill in the gaps here!

**Comment by cjappl** [comment]
Perfect! They are 100% the people to have something good. Keep me posted if I can help at all :)

**Comment by cjappl** [comment]
@teddywilson and @underpickled I have forked and cloned the repo, and am ready to update when we have the message text! I will submit a PR for Oakland, so count on me to complete this one! 

Thanks for making the design as easy as possible to replicate

**Comment by cjappl** [comment]
Heard from a contact at APTP, working on a statement, and I'm trying to get them moving as fast as possible!

**Comment by underpickled** [comment]
@cjappl that's awesome! I haven't heard back since I reached out, but I'm glad you were able to reach them.

**Comment by starchy** [comment]
See also issue #92 and don't forget City Council President/Councilmember at Large Rebecca Kaplan, atlarge@oaklandca.gov.

**Comment by serifluous** [comment]
Template proposed in issue #297
