### ISSUE TITLE
San Francisco, CA

### ISSUE THREAD

**Issue by jordanscode** [teddywilson/defund12.org#105]
**Subject:** San Francisco Resident for Defunding the SFPD

**Emails**
- MayorLondonBreed@sfgov.org
- Board.of.Supervisors@sfgov.org
- sandra.fewer@sfgov.org
- Catherine.Stefani@sfgov.org
- Aaron.Peskin@sfgov.org 
- marstaff@sfgov.org
- prestonstaff@sfgov.org
- Norman.Yee@sfgov.org
- mandelmanstaff@sfgov.org
- ronenstaff@sfgov.org
- waltonstaff@sfgov.org
- Ahsha.Safai@sfgov.org

**Content**
To Mayor Breed and the San Francisco Board of Supervisors, 	

My name is [your name], and I am a resident of San Francisco. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue. 	

SFPD has been a waste of our resources. Last year, the SFPD budget was $611,701,869. The majority of which comes right from the San Francisco general fund. While we've been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police. 

I call on you to slash the SFPD budget and instead use those extraordinary resources towards solving our homeless problem and mental health crisis which are felt most by our black neighbors and veterans. We implore you to give every member of our community experiencing homelessness a place to call home and the treatment they need.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,
[your name]

**Comment by gasolinesunsets** [comment]
Can we add **Elected Officers** to this template please? 

Carmen.Chu@sfgov.org
cityattorney@sfcityatty.org
districtattorney@sfgov.org
sfso.complaints@sfgov.org
jose.cisneros@sfgov.org
manohar.raju@sfgov.org

**Comment by Ceshion** [comment]
I will add this template

**Comment by Ceshion** [comment]
> 
> 
> Can we add **Elected Officers** to this template please?
> 
> [Carmen.Chu@sfgov.org](mailto:Carmen.Chu@sfgov.org)
> [cityattorney@sfcityatty.org](mailto:cityattorney@sfcityatty.org)
> [districtattorney@sfgov.org](mailto:districtattorney@sfgov.org)
> [sfso.complaints@sfgov.org](mailto:sfso.complaints@sfgov.org)
> [jose.cisneros@sfgov.org](mailto:jose.cisneros@sfgov.org)
> [manohar.raju@sfgov.org](mailto:manohar.raju@sfgov.org)

should the greeting language change to reflect this? i.e. 
  To Mayor Breed, the San Francisco Board of Supervisors, and San Fransisco Elected Officers

**Comment by Ceshion** [comment]
#134

**Comment by averymcguirt** [comment]
As far as I can tell, this is all published now. Going to close the issue.

**Comment by bird25** [comment]
I'm wondering if we can add the Board of Education commissioners in the list of elected officials? In San Francisco, the Education commissioners are elected, and the school district has a contract with our police department, and school budget includes a line item for the police.

Unfortunately, I haven't found a board of education email, but each education commissioner's email is listed on the [BoE website](https://www.sfusd.edu/about/board-of-education)

MarkSanchez@sfusd.edu; 
GabrielaLopez@sfusd.edu; 
AlisonMCollins@sfusd.edu; 
StevonCook@sfusd.edu; 
JennyLam@sfusd.edu; 
FaauugaMoliga@sfusd.edu;
RachelNorton@sfusd.edu;

**Comment by Ceshion** [comment]
@averymcguirt referring this one to you :)

**Comment by averymcguirt** [comment]
Perhaps some brief language to add to the message body regarding police in schools would make this addition of recipients make more sense?
@bird25  would you like to suggest some language?

**Comment by bird25** [comment]
@averymcguirt I copied the language from [St. Paul](https://defund12.org/stpaul-schoolboard)

I think it may make sense to insert this between paragraph 2 and 3: 

> Furthermore, I recognize the importance of education. It is imperative that Black students are free from police violence and terror in their schools. That is not possible if the district continues its relationship with SFPD. I urge SFUSD to follow the lead of Minneapolis Public Schools, and take action to divest from policing in the district. 
> 
> To that end, I demand that SFUSD immediately terminate all of their relations with the SFPD. SFPD enacts the same violence in our own communities as we have seen this week in Minneapolis, and through these relations our public schools support this violence and continue to uphold the white supremacy that is foundational to this country.
