### ISSUE TITLE
Please add Philadelphia, PA! Thank you!

### ISSUE THREAD

**Issue by vulichney** [teddywilson/defund12.org#109]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email: "defund PPD"
* A list of emails (at least one) for the government officials you’d like to receive the message: 
City Council members +legislative staffers: 
Cindy Bass Cindy.Bass@Phila.gov
Legislative Staffer – Rodnie Jamison Rodnie.jamison@phila.gov
Kendra Brooks Kendra.Brooks@phila.gov
Legislative Staffer – Alison Stohr Alison.Stohr@phila.gov
Kenyatta Johnson Kenyatta.Johnson@Phila.gov
Legislative Staffer – Joshu Harris Joshu.Harris@Phila.gov
Legislative Staffer – Brett Nedelkoff Brett.Nedelkoff@phila.gov
Helen Gym Helen.Gym@phila.gov
Legislative Staffer – Shanee Garner Shanee.Garner@phila.gov
Jamie Gauthier Jamie.Gauthier@phila.gov
Legislative Staffer – Max Weiss Max.Weiss@Phila.gov
Maria Q Sanchez Maria.Q.Sanchez@phila.gov
Legislative Staffer – Eric Bodzin Eric.Bodzin@Phila.gov
Derek Green Derek.Green@phila.gov
Legislative Staffer – Frank Iannuzzi Frank.Iannuzzi@Phila.gov
Legislative Staffer – Duwayne Terry Duwayne.Terry@Phila.gov
Curtis Jones.Jr Curtis.Jones.Jr@phila.gov
Legislative Staffer – Samantha Williams Samantha.Williams@Phila.gov
Bobby Henon bobby@bobbyhenon.com
Legislative Staffer – Lauren Atwell Lauren.Atwell@phila.gov
Katherine Gilmore Richardson Katherine.Gilmore. Richardson@phila.gov
Legislative Staffer – Shawn Baldwin Shawn.Baldwin@Phila.gov
Allan Domb Allan.Domb@Phila.gov
Legislative Staffer – Eryn Santamoor Eryn.Santamoor@Phila.Gov
Legislative Staffer – Laurel Grbach Laurel.Grbach@phila.gov
Cherelle Parker Cherelle.Parker@Phila.gov
Legislative Staffer – Rachel Meadows Rachel.Meadows@Phila.gov
Isaiah Thomas Isaiah.Thomas@phila.gov
Legislative Staffer – Dan Lodise Daniel.Lodise@Phila.gov
David Maynard David.Maynard@phila.gov
Darrell Clarke Darrell.Clarke@phila.gov
Legislative Staffer – Jessica Sanchez Jessica.Sanchez@Phila.gov
Legislative Staffer – Mary McDaniel Mary.McDaniel@Phila.gov
David Oh David.Oh@Phila.gov
Legislative Staffer – Tyler DeBusi Tyler.DeBusi@Phila.gov
Brian ONeill Brian.ONeill@phila.gov
Legislative Staffer – Robert Yerkov Robert.Yerkov@Phila.gov
Mark Squilla Mark.Squilla@Phila.gov
Legislative Staffer – Sean Mcmonagle Sean.Mcmonagle@phila.gov

City’s Managing Director – Brian Abernathy – brian.abernathy@phila.gov
Mayor of Philadelphia – Jim Kenney – James.kenney@phila.gov

* A detailed message concerning the budgeting decisions that are at stake in your community
"To whom it may concern,            

My name is [NAME], and I am a resident of [CITY, STATE]. Mayor Kenney’s proposed Philadelphia budget for fiscal year 2021 has proposed a $14 billion increase for the Philadelphia police department during a time of economic strife and while other essential social budgets that support the community are being slashed: for example, budgets for library, homeless services, Parks and Recreation, and public health (during the global COVID-19 pandemic!) are all being slashed and the city is eliminating its budget for arts and culture entirely. 

I urge you to consider pressuring the office of the mayor towards an ethical and equal reallocation of the Philadelphia expense budget, away from PPD, and towards social services and education programs, effective at the beginning of FY 21.          

I am emailing to ask city officials to please reject any proposed budget that increases taxpayer spending on police while cutting funding for important social and community projects. I am asking that city officials lobby the same amount of attention and effort towards finding sustainable, long term change.            

Black Lives Matter.            
Sincerely,            
[NAME]"

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by cstrouse** [comment]
Philadelphia was included in both #42 and #96

**Comment by teddywilson** [comment]
Since Philadelphia was already added I'm going to close this out. Feel free to make a PR against the current Philadelphia template.
