### ISSUE TITLE
Hudson Valley, NY!

### ISSUE THREAD

**Issue by a31212** [teddywilson/defund12.org#115]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by a31212** [comment]
please

**Comment by teddywilson** [comment]
Hey, please add the data listed above and we will get Hudson Valley live!

Unfortunately we don't have the bandwidth to create the email templates on our own at the moment as we are flooded with requests.

**Comment by teddywilson** [comment]
Since we have quite a few requests, please open a new issue with the required fields. Thanks!

**Comment by cstrouse** [comment]
Common Council President: 
Tom DePietro
email: councilpres@cityofhudson.org

Alderman, 1st Ward  
Jane Trombley
email: : jane.trombley@cityofhudson.org

Rebecca Wolff
email: rebecca.wolff@cityofhudson.org

Alderman, 2nd Ward 
Dewan Sarowar
email: dewan.sarowar@cityofhudson.org

Tiffany Garriga
email:  tiffany.garriga@cityofhudson.org


Alderman, 3rd Ward  
Shershah Mizan
email: Shershah.mizan@cityofhudson.org

Calvin Lewis, Jr.
email: calvin.lewis@cityofhudson.org

Alderman, 4th Ward  
Malachi Walker
email:  malachi.walker@cityofhudson.org

John S. Rosenthal
email: John.rosenthal@cityofhudson.org

Alderman, 5th Ward 
Eileen Halloran
email: eileen.halloran@cityofhudson.org

Dominic Merante
email: Dominic.merante@cityofhudson.org
