### ISSUE TITLE
Los Banos Mayor and Council members 

### ISSUE THREAD

**Issue by amartineez** [teddywilson/defund12.org#116]
Los Banos Mayor: mike.villalta@losbanos.org

Los Banos Council Members:  tom.faria@losbanos.org
deborah.lewis@losbanos.org
daronica.johnson-santos@losbanos.org
brett.jones@losbanos.org

Subject line: We Demand a People's Budget

Dear Mayor Michael Villalta and Council members, 

My name is [NAME] and I am a resident of Los Banos.  I am emailing today to demand that you vote no on the Mayor's FY21 proposed budget. Furthermore, I urge you to pressure the office of the mayor towards an ethical and equal reallocation of the Los Banos expense budget, away from LBPD and towards social services and education programs, effective at the beginning of FY21. 

I urge you and the rest of the city council to amend or deny the proposed budget for 2021. Redirect money away from LBPD and into social service programs that will benefit public health and our own communities, especially communities of color. The proposed budget for 2019-2020 suggests that the largest fraction of the city’s budget should go to policing ($14,881,614), which is over 24% larger than even the second largest allocation of funds, fire ($5,268,311). If this is truly representative of the council’s thoughts on how funds should be allocated, I am ashamed to call Los Banos my home and I am ashamed to call you my elected officials.

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really "fight crime," we don't need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We don't need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Villalta, will you look out for me, and will you look out for us?

Thank you,

[YOUR NAME]

**Comment by Ceshion** [comment]
I will get started adding this template

**Comment by Ceshion** [comment]
added in #129

**Comment by amartineez** [comment]
> added in #129

I forgot to add the state California

**Comment by Ceshion** [comment]
> 
> 
> > added in #129
> 
> I forgot to add the state California

don't worry, I got you ❤️
