### ISSUE TITLE
Philadelphia

### ISSUE THREAD

**Issue by annasugrue** [teddywilson/defund12.org#12]
Philly We Rise has all of the information about the Philly city budget and the names and email addresses of city council people, and I think they would benefit from an easy defund12.org link. See Philly We Rise's work here: http://phillywerise.com/defundpolice/

**Comment by averymcguirt** [comment]
We are currently handling a lot of requests - if you could include a detailed (but succinct) message it would greatly speed up our addition of Philly!
Thank you!!

**Comment by annasugrue** [comment]
Dear Philadelphia City Council Members, 

My name is [x] and I am a resident of the city of Philadelphia. Our Mayor Jim Kenney has proposed a city budget for FY21 that slashes $370 million from public services while funneling nearly $23 million in new funds to law enforcement. I am emailing today to demand that you vote No on the Mayor's proposed budget. Furthermore, I urge you to pressure the office of the mayor towards an ethical and equal reallocation of the Philadelphia expense budget, away from PPD and towards social services and violence prevention programs that support your fellow Philadelphians. At a moment when our country is coming to grips with the realities of police violence, the City of Philadelphia should lead by example by making a fiscal dedication to uplift communities and not cops.  

Thank you,
[x]

**Comment by averymcguirt** [comment]
I will close this for now, as we have a few letters for Philly now live on the site. We are currently discussing how do deal with multiple different letters for individual cities. I will close this for now, but if you find any language lacking let us know! 

Thank you!
