### ISSUE TITLE
Please add San Diego, California to the queue.

### ISSUE THREAD

**Issue by pazfabela** [teddywilson/defund12.org#121]
The issues in San Diego, California are arising fast like many other states. The protest in La Mesa was despicable on the police's end as the protest started out tranquil before peaceful protestors were assaulted and had tear gas deployed upon them. I am in disgust with how many people were harmed fatally for simply fighting for their rights, it is their first amendment under the constitution to freedom of speech/ ensemble and yet they were viciously attacked for respecting so. Following the La Mesa protest, it is seen in a later protest taking place in Downtown San Diego, tear gas was deployed on another group of protestors simply playing music and dancing. The cops need to be held reliable for their actions, whether it be charges or defunding them, accountability must be taken. Thank you.

**Comment by teddywilson** [comment]
This is very unfortunate - I 100% agree with you.

Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Would love to get San Diego on the site, so definitely follow up - thank you!!

**Comment by pazfabela** [comment]
Thank you for the regard, Teddy, I'll follow up as soon as I can. I appreciate it!
