### ISSUE TITLE
Addition - Pittsburgh, PA

### ISSUE THREAD

**Issue by bluemoonkat** [teddywilson/defund12.org#127]
Subject: Divest Funds From Police back into Pittsburgh Community

Mayor Bill Peduto: bill.peduto@pittsburghpa.gov

Council Members and Chiefs/Assistant Chief of Staff: theresa.kail-smith@pittsburghpa.gov, brosha.tkacheva@pittsburghpa.gov, district5@pittsburghpa.gov, district7@pittsburghpa.gov, erika.strassburger@pittsburghpa.gov, emilie.yonan@pittsburghpa.gov, reverend.burgess@pittsburghpa.gov, daniel.wood@pittsburghpa.gov, curt.conrad@pittsburghpa.gov, blake.plavchak@pittsburghpa.gov, Kim.Salinetro@pittsburghpa.gov, 
sally.stadelman@pittsburghpa.gov 

Hello,

I am writing to demand the city stops increasing the Pittsburgh Police Budget and redirects funding into supporting community operations.

The Pittsburgh Operating Budget's total designated expenditures allocate 40.0% to Public Safety and only 10.5% to Public Works.  This is unacceptable.

The 2020 budget for the Bureau of Police is $114,787,000.  This is ~18.9% - nearly one fifth - of the overall City Operations Budget.

There is only $1,758,022 allocated to the Office of Equity.  The Ethics Hearing Board budget went down by $6,974 from 2019-2020 while the Police Bureau budget increased by $10,241,674.  What is the need for this increase?  

The first 2020 goal listed in the Bureau overview is “Continue to increase the ‘boots on the ground’ officers in the field”.  Is this what the increase will go toward? What is the reasoning for needing more police on the ground? Due to the overwhelming evidence that the police are targeting Black people in this city (and across the world), it is the correct move to divest from funding boots on the ground operations and invest in upholding policies that support the people.

The Neighborhood and Community Development fund was only allocated $7,502,080 for 2020. That is ~6.8% of the 2020 Capital Budget.  This is not enough. I demand you take action to re-allocate money away from the Pittsburgh Police and back into community development that includes affordable housing and reparations for Black citizens.  Both the state and the Pittsburgh Police owe the Black community a great debt.

It is clear that Pittsburgh Police funds are not being appropriately used to maintain safety and freedom on the streets of Pittsburgh.  This is not only obvious by the City Budget, it is obvious by how Pittsburghers are treated by the police. Black Pittsburghers are disproportionately subject to this violence. Antwon Rose was shot dead in our city by a police officer and we will always remember.  Elijah Brewer was shot dead in our city by a police officer and we will always remember.

Sincerely,

[your name]

**Comment by Ceshion** [comment]
Thank you! I'll start adding this.

**Comment by Ceshion** [comment]
added in #156
