### ISSUE TITLE
Please add Cambridge, MA

### ISSUE THREAD

**Issue by jsstoroz** [teddywilson/defund12.org#130]
Emails: council@cambridgema.gov, citymanager@cambridgema.gov, mayor@cambridgema.gov
Subject: Reduce the Cambridge Police Department budget
Message: 
(Don't forget to replace the [x]'s with your information!) 
Dear City Councilors, Mayor Siddiqui, and City Manager DePasquale,

The City of Cambridge must reduce the Cambridge Police Department budget. Cambridge’s needs must be addressed by the provision of care, and not the threat of violence. We must invest in public services that build towards “a free and fair society” rather than an armed force that endangers us.

Our city faces racial inequalities, borne from historical injustice and brought into sharp relief by the COVID-19 epidemic, that can’t be solved by policing. Members of our community live in tight quarters and on lean budgets— this before a pandemic stole three months of wages, and counting. Thousands of us are becoming food-insecure and are at risk of eviction as soon as the ban is lifted. Essential educators are living on starvation pay while repeated and overwhelming community demands to right this glaring injustice are ignored. 

Meanwhile, the Police Department is the single largest expenditure in the City’s General Fund behind loan repayments. The CPD currently spends 52% of its budget on patrolling - $33,000,000 - or 7x as much spending on patrol than social justice initiatives. 

Now especially, the City Council can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities - starting with cutting the least transparent and most harmful parts of the CPD budget.

Racist police violence doesn’t just happen in other cities - it happens here in Cambridge too. The City Council must stop investing in targeted criminalization and surveillance, and fund what Black and Brown communities need to be safe and healthy: COVID19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.

Thank you, [Name/Location]

**Comment by Ceshion** [comment]
Thank you! added in #160
