### ISSUE TITLE
hannahrrawdon@gmail.com

### ISSUE THREAD

**Issue by hanbanzita** [teddywilson/defund12.org#139]
Please add Kansas City, Missouri!!!
https://governor.mo.gov/contact-us
MayorQ@kcmo.org
sunshinerequest@ago.mo.gov.
moaudit@auditor.mo.gov
info@cleaverforcongress.com

Budget issues include not enough funding for public schools in the state of Missouri. More funding for body cams/data storage for KCPD. Budget cuts to the arts.
-- this article lays it out better--
https://www.kcur.org/government/2020-02-20/what-you-need-to-know-about-kansas-citys-proposed-cuts-to-arts-economic-development-health

**Comment by hanbanzita** [comment]
Please add Kansas City, Missouri!!!
https://governor.mo.gov/contact-us
MayorQ@kcmo.org
sunshinerequest@ago.mo.gov.
moaudit@auditor.mo.gov
info@cleaverforcongress.com

Budget issues include not enough funding for public schools in the state of Missouri. More funding for body cams/data storage for KCPD. Budget cuts to the arts.
-- this article lays it out better--
https://www.kcur.org/government/2020-02-20/what-you-need-to-know-about-kansas-citys-proposed-cuts-to-arts-economic-development-health

**Comment by teddywilson** [comment]
Hey we'd love to add KC! Unfortunately we need a bit more information as we're processing a ton of requests. Would you mind reopening the issue with the email template, subject line, and this list of recipients??

Going to close this out, as we're only keeping open valid issues, but please just go ahead and make a new one!
