### ISSUE TITLE
Please add Austin, Texas!! 

### ISSUE THREAD

**Issue by obitobito** [teddywilson/defund12.org#143]
AustinTexas.gov/budget shows the budget of APD compared to other services like parks and recreation and emergency health services. APD budget is massive compared to others. Lmk if anymore info is needed

**Comment by obitobito** [comment]
AustinTexas.gov/budget shows the budget of APD compared to other services like parks and recreation and emergency health services. APD budget is massive compared to others. Lmk if anymore info is needed

**Comment by jamespeacock** [comment]
handled by #50
