### ISSUE TITLE
Rockland County

### ISSUE THREAD

**Issue by msveryberry** [teddywilson/defund12.org#15]
Rockland is right over the river. A majority of people in Rockland county are racist and deflect any or all topics of racism. They express racism in many Facebook groups and even delete posts that do not fit their agenda. This county needs major change. There is not enough diversity!  We have to expand and we have to do it together.

**Comment by msveryberry** [comment]
Rockland County is in NY. Right across the bridge from Westchester/Yonkers. Right next to NJ.

**Comment by besand** [comment]
Especially individual districts within Rockland County aside from the Rockland County Sheriff: Town of Orangetown, Town of Ramapo, Town of Clarkstown

**Comment by carrieham** [comment]
Hello!

Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!
