### ISSUE TITLE
Buffalo, NY

### ISSUE THREAD

**Issue by cheung31** [teddywilson/defund12.org#154]
## Email Sourcing
* Sources:
  * Mayor: https://webcache.googleusercontent.com/search?q=cache:D7KWeX3I7CoJ:https://www.buffalony.gov/Directory.aspx%3FDID%3D98+&cd=2&hl=en&ct=clnk&gl=us
  * Common Council: https://webcache.googleusercontent.com/search?q=cache:_vj0ByJJR_sJ:https://www.buffalony.gov/Directory.aspx%3Fdid%3D65+&cd=2&hl=en&ct=clnk&gl=us
* Ran following in JavaScript console:
```javascript
const emails = [];
document.querySelectorAll("td a[href^=mailto]").forEach(a => { e = a.href.split("mailto:")[1]; emails.push(e); });
emails.map(e => `[${e}](mailto:${e})`).join("\n* ");
```

## Content

**Subject:** Buffalo, NY Resident for Defunding the BPD

**Emails**

* [mayor@city-buffalo.com](mailto:mayor@city-buffalo.com)
* [jferoleto@city-buffalo.com](mailto:jferoleto@city-buffalo.com)
* [dpridgen@city-buffalo.com](mailto:dpridgen@city-buffalo.com)
* [dfranczyk@city-buffalo.com](mailto:dfranczyk@city-buffalo.com)
* [mertha@city-buffalo.com](mailto:mertha@city-buffalo.com)
* [jmontour@city-buffalo.com](mailto:jmontour@city-buffalo.com)
* [jpaul@city-buffalo.com](mailto:jpaul@city-buffalo.com)
* [vshaw@city-buffalo.com](mailto:vshaw@city-buffalo.com)
* [sgould@city-buffalo.com](mailto:sgould@city-buffalo.com)
* [tstjean@city-buffalo.com](mailto:tstjean@city-buffalo.com)
* [wdoll@city-buffalo.com](mailto:wdoll@city-buffalo.com)
* [dthomas@city-buffalo.com](mailto:dthomas@city-buffalo.com)
* [choyt@city-buffalo.com](mailto:choyt@city-buffalo.com)
* [mnowakowski@city-buffalo.com](mailto:mnowakowski@city-buffalo.com)
* [rfontana@city-buffalo.com](mailto:rfontana@city-buffalo.com)
* [uwingo@city-buffalo.com](mailto:uwingo@city-buffalo.com)
* [darivera@city-buffalo.com](mailto:darivera@city-buffalo.com)
* [jgolombek@city-buffalo.com](mailto:jgolombek@city-buffalo.com)
* [cscanlon@city-buffalo.com](mailto:cscanlon@city-buffalo.com)
* [rwyatt@city-buffalo.com](mailto:rwyatt@city-buffalo.com)

**Content**
To City of Buffalo Mayor & Common Council,

My name is [your name], and I am a resident of Buffalo. The incident as reported by WBFO (NPR) on June 4, 2020 is appalling and inhumane. This is a display of egregious police brutality. Please watch the video if you are not familiar: https://twitter.com/wbfo/status/1268712530358292484. This should speak for itself in justifying the immediate need to defund the BPD.

Sincerely,
[your name]

**Comment by ceebs** [comment]
Opened PR - https://github.com/teddywilson/defund12.org/pull/161

**Comment by teddywilson** [comment]
Thank you, we will take a look!

**Comment by cheung31** [comment]
Thank you @ceebs  @Ceshion  @teddywilson  @ctneal91 for quick turnaround. 🙏
