### ISSUE TITLE
Can you amend the LA email please?

### ISSUE THREAD

**Issue by JessHannah** [teddywilson/defund12.org#165]
can you update LA email to reflect the changes yesterday and to urge that the 5% increase is not nearly enough? We don't want council members to read this email and feel like they already addressed what we are demanding. They need to DO BETTER. Thank you!

**Comment by teddywilson** [comment]
Yes, we will take a look! @averymcguirt thoughts?

**Comment by averymcguirt** [comment]
Hi @JessHannah thanks for flagging this. I've changed some language to reflect this, and will close the issue. Though if you have specific suggestions feel free to draft and reopen or start a new issue.
