### ISSUE TITLE
2020 Toronto Police Budget Call for Action/ Defunding

### ISSUE THREAD

**Issue by largeinsect** [teddywilson/defund12.org#168]
This document includes a template for Toronto and hyperlinks to templates for other Canadian cities

FTP 
ACAB
Canada is just.as.bad.

https://docs.google.com/document/d/1roduncOZ_y0C_oWIMIQ6yV-13fZqck0i54RZoPSwYBw/mobilebasic?fbclid=IwAR1k7i2kF35EsABSeHG_OKR7bu4EVq2ZKBtxPVzQUVoTsnyTaAIPEz66bFo

**Comment by teddywilson** [comment]
We will take a look - thanks for sharing!
