### ISSUE TITLE
Add Minneapolis and St. Paul council members and mayors

### ISSUE THREAD

**Issue by crashdamag** [teddywilson/defund12.org#17]
Please add Minneapolis & St. Paul!

**Comment by carrieham** [comment]
Hello!

Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!
