### ISSUE TITLE
A San Diego request!

### ISSUE THREAD

**Issue by pazfabela** [teddywilson/defund12.org#177]
San Diego resident's request to restructure our budget.

kevinfaulconer@sandiego.gov

barbarabry@sandiego.gov

jennifercampbell@sandiego.gov

christopherward@sandiego.gov

monicamontgomery@sandiego.gov

markkersey@sandiego.gov

chriscate@sandiego.gov

scottsherman@sandiego.gov

vivianmoreno@sandiego.gov 

georgettegomez@sandiego.gov

My name is [your first and last name here] and I'm a resident of San Diego, California. I am emailing both the mayor and city council today in hopes of spreading awareness towards adopting a People's Budget. I believe it would greatly benefit our community if we restructured funding from our police towards the prioritization within our community wellness.

The issues in San Diego are arising fast like many other states. The police during the protest in La Mesa were despicable, deploying rubber bullets alongside tear gas canisters within a peaceful group is not justifiable. Why is it that their money is going into riot gear and not education on what to do with our civilians simply standing up for their rights, which is protected under the constitution as their first amendment, the right to assemble and have freedom of speech. San Diego is titled America's finest city and yet there are videos on the media of your officers deploying tear gas on a blissful group in Downtown, it is seen in the video that the group was merely playing music and dancing while protesting. That fails to paint us as a fine city.

With less of the SDPD's funding going towards an uncivil and unjust matter, it could instead be refocused on our high rate of homeless and homeless veterans, who, ironically fight for our freedom yet are being exposed to police brutality as well. Another point to take note of, is how much funding there could be in light of the Coronavirus epidemic, your healthcare workers are very much underprepared and overworked and yet there is a proposed $27,000,000 increase for our city's police. Additionally, many of the small businesses that assist San Diego's economy and make San Diego the beautiful city we are today are being shut down due to the global pandemic because they are left without funds to run their business further.

Please reconsider.

Thank you,

[Your first and last name]

**Comment by lleadbet** [comment]
Was added in #193. 

@pazfabela - if you have suggestions for the text, put them here.

**Comment by pazfabela** [comment]
Nothing further, thank you so much I can't express how grateful I am for you to be putting San Diego up there.
