### ISSUE TITLE
Possible to Add a Copy + Paste Option?

### ISSUE THREAD

**Issue by kevinzweerink** [teddywilson/defund12.org#18]
In my experience there are many issues with mailto links. Personally they have not worked in my browser for years and I can't figure out why. I would be surprised if I were the only person with this issue.

Would it be possible to add a view that makes it easy to copy and paste recipients, subject, and email body? Happy to put together a quick design if helpful.

**Comment by minicreative** [comment]
We're in the process of working on this right now! Thanks so much for your input

**Comment by kevinzweerink** [comment]
Awesome! Thanks for the response!

**Comment by minicreative** [comment]
@kevinzweerink Links still open `mailto` data by default (we think this is most effective), but the browser window now displays the recipients, body, etc. with buttons for copy/paste. The list of cities/emails supports copy/paste as well. Thanks for your input, and let us know if we missed something!
