### ISSUE TITLE
Portland Oregon 

### ISSUE THREAD

**Issue by pcnap** [teddywilson/defund12.org#180]
Please add a Portland Oregon quick email

**Comment by pcnap** [comment]
Subject: Sheriff Department Budget Requests

Hello Multnomah County commissioners, 

My name is [your name] and I live in Portland OR. I am writing to urge that the county divest from the systems of incarceration and policing, and instead invest in life affirming, sustainable, and self-determined community resources. 

Many community members in Multnomah County were in crisis prior to COVID-19, and while we do not yet know the full impact of this pandemic, we know that those who will be most affected by it are communities who are already socially and economically marginalized.

Now, when the need for supportive services is even greater, the county has instead proposed increases towards programs like gang enforcement teams, electronic monitoring, body cameras, and increased jail funding. 

County officials have a responsibility to respond to this crisis by distributing resources that allow communities to survive and thrive - solutions can not revolve around criminalization, jail time, houseless encampment sweeps, or the surveillance and harassment of Black neighborhoods and immigrant communities through anti-gang policing.

Funding toward life-affirming resources such as those related to housing, access to health care, and food security, must be prioritized, especially in the midst of a major budget shortfall. Difficult decisions made now will have reverberating impacts well into our future. We can make the choice to fund people, not policing & incarceration.

Our demands are:

Reject the $6.4 million increase to the Sheriff’s Department

Divest from Homeless Outreach and Programs Engagement (HOPE) and instead direct resources towards dignified temporary and permanent 
housing and rent relief; halt sweeps of houseless encampments and other villages.

Reject increased funding and divest from Adult Electronic Monitoring, Adult Field Supervision. 

Reject increased funding and divest from Body Worn Camera programs.

Deny the Sheriff Department’s proposition to use $1.08 million from the general fund to keep Dorm 15 at Inverness Jail from closing. 

Divest from the Juvenile East Multnomah Gang Enforcement Team & the Gang Enforcement Deputy.

Invest in life affirming solutions to Multnomah County’s needs by building up community-based and peer-led services and resources. No reductions in the Housing Stabilization for Vulnerable Populations, an d the Aging, Disability, and Veterans Services Division (ADVSD) Safety Net Program.

A 2% cut across all programs fails to address that some programs sustain networks for survival, while others do not. The economic impact of COVID-19 instead requires a complete reimagining of how we allocate county resources, and makes clear the necessity for prioritizing investments in communities’ health and well-being. The county can address its $58 million (and growing) deficit in the $1.98 billion budget by divesting from the violence of policing and incarceration. The systems of policing and incarceration have no role in public health or safety; prisons and jails are vectors for the spread of COVID-19 and have always been antithetical to public health. 
Existing racial and economic disparities will only worsen in the wake of this ongoing crisis. We know that this virus is disproportionately affecting Black and brown communities & that this disparity is caused by racist systems that affect how and when people receive care. 

Action now to invest in long-term, and life sustaining resources will serve to insulate our communities from the effects of this pandemic in the future. We know that meeting the basic needs of our communities is the only way to ensure their health and safety.

Thank you,

[your name]

**Comment by teddywilson** [comment]
I saw you submitted two issues (e.g., https://github.com/teddywilson/defund12.org/issues/181)

Feel free to close out one of them so we can de-duplicate!

**Comment by Ceshion** [comment]
I'm starting on this one now! Please close #181 and keep this as the main request

**Comment by Ceshion** [comment]
added in #352
