### ISSUE TITLE
Request for Louisville, Kentucky - #JusticeforBreonnaTaylor

### ISSUE THREAD

**Issue by blackhattravels** [teddywilson/defund12.org#184]
Drafted this for folks in Louisville in relation to the Breonna Taylor case. I'm surprised this didn't exist yet, it could be really useful.

--

**SUBJECT:** Reallocate Funding for the LMPD 

**EMAILS:**

Councilwoman Jessica Green - jessica.green@louisvilleky.gov

Councilwoman Barbara Shanklin - barbara.shanklin@louisvilleky.gov

Councilwoman Keisha Dorsey - keisha.dorsey@louisvilleky.gov

Councilwoman Barbara Sexton Smith - barbara.sextonsmith@louisvilleky.gov
 	 
Councilwoman Donna Purvis - donna.purvis@louisvilleky.gov

Councilman David James - david.james@louisvilleky.gov
 	 
Councilwoman Paula McCraney - paula.mccraney@louisvilleky.gov

Councilman Brandon Coan - brandon.coan@louisvilleky.gov
 	 
Councilman Bill Hollander - bill.hollander@louisvilleky.gov

Councilman Pat Mulvihill - pat.mulvihill@louisvilleky.gov
 	 
Councilman Kevin Kramer - kevin.kramer@louisvilleky.gov

Councilman Rick Blackwell - rick.blackwell@louisvilleky.gov
 	 
Councilman Mark Fox - mark.fox@louisvilleky.gov

Councilwoman Cindi Fowler - cindi.fowler@louisvilleky.gov
 	 
Councilman Kevin Triplett - kevin.triplett@louisvilleky.gov

Councilman Scott Reed - scott.reed@louisvilleky.gov
 	 
Councilman Markus Winkler - markus.winkler@louisvilleky.gov

Councilwoman Marilyn Parker - marilyn.parker@louisvilleky.gov
 	 
Councilman Anthony Piagentini - anthony.piagentini@louisvilleky.gov

Councilman Stuart Benson - stuart.benson@louisvilleky.gov
 	 
Councilwoman Nicole George - nicole.george@louisvilleky.gov

Councilman Robin Engel - robin.engel@louisvilleky.gov
 	 
Councilman James Peden - james.peden@louisvilleky.gov

Councilwoman Madonna Flood - madonna.flood@louisvilleky.gov
 	 
Councilman David Yates - david.yates@louisvilleky.gov

Councilman Brent Ackerson - brent.ackerson@louisvilleky.gov

**MESSAGE:**

Hello, 

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the Louisville Metro Government’s inordinate investment in the Louisville Metro Police Department (LMPD) in light of the death of Breonna Taylor, a 26-year old Black woman who was killed by three LMPD police officers earlier this year on March 13th. The case, which has made national headlines, has drawn rebuke and protest from thousands of people in the metro area, along with its mishandling and lack of appropriate corrective actions regarding the officers involved.

I am therefore writing to demand that the Metro Council consider reapportion of general funds away from the LMPD and towards the existing Criminal Justice Commission, social services and education programs, effective at the beginning of FY21, July 1, 2020. It is morally reprehensible to dedicate over $190 million dollars of the city’s available funds (approximately 32%), with only $4 million allocated to the Criminal Justice Commission and much less to various social services, while increasing police presence and allowing condemnable actions from LMPD officers to go unexcused. Through a reallocation of funds, we can promote the well-being of citizens and reduce crime by sourcing community-based solutions, allowing residents to become invested in providing recommendations for improvements in criminal justice system operations and to engage in creating solutions that best serve their communities and their needs.

I also urge Metro Council to enact legislation that holds police members accountable and to overturn policies that allow police members to engage in unlawful behavior with impunity, that an elected Civilian Police Accountability Council be established with real reform powers, and that abusive or reckless officers, including the officers involved in Breonna Taylor's death, be fired and criminally charged. Ending any unfair secretive internal LMPD review process would be a good first step in achieving this goal. 

I ask that all council members lobby the same amount of attention and effort towards fostering sustainable, long-term change, to prevent further tragedies at the hands of the police, and to take immediate action for the well-being of all of our residents. 

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by teddywilson** [comment]
Thank you so much! We will review this and get Louisville up and rolling!!!!

**Comment by jamespeacock** [comment]
I will update these requested changes on the currently open PR #37

**Comment by blackhattravels** [comment]
Hello all,

I apologize for the delay — I’m just now getting a chance to reply to email. But I now these that my template was approved, and also that there’s another Louisville email! How grand! Thank you so much for your swift and brilliant work on this. Communities really need tools like these and they’re deeply appreciated.

Thank you so, so much!

In solidarity,
Keith

—

Keith Brooks
+1 502.649.7927
Web: http://keithbrooks.co
Instagram: keithbrooks

This message was sent from a mobile device. Please excuse errors in brevity and text.
