### ISSUE TITLE
Please add Seattle, Washington

### ISSUE THREAD

**Issue by lydritch** [teddywilson/defund12.org#188]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email : LETTER TO MAYOR AND CITY COUNCIL MEMBERS
******* MAYOR EMAIL:  jenny.durkan@seattle.gov CITY COUNCIL: COUNCIL@SEATTLE.GOV , lisa.herbold@seattle.gov , tammy.morales@seattle.gov , kshama.sawant@seattle.gov , alex.pedersen@seattle.gov , debora.juarez@seattle.gov , dan.strauss@seattle.gov , andrew.lewis@seattle.gov , teresa.mosqueda@seattle.gov , lorena.gonzalez@seattle.gov , 
******* DEFUND SPD and reallocate egregious police budgets towards education, social services, and dismantling racial inequality.

I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the SPD’s well documented history of murdering Black people. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

We are in the midst of a pandemic with severe economic consequences. When people are unemployed, they cannot pay rent. Prior to the pandemic, 60k people were unhoused; the evictions and economic insecurity caused by COVID-19 will bring that number even higher.

Support for communities in need is necessary now, more than ever. But instead, the Mayor has proposed an increase in funding to the SPD, despite the fact that crime has fallen considerably during the past few months. The SPD has seen a rise in overtime pay which, more often than not, is paid out to officers responsible for harassing the unhoused, and Black, Indigenous, people of color.

We demand that the City Council defund the SPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Seattleites during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Although City Council has avoided voting or revising Mayor Durcan's draconian budget proposal, the document is back in your hands. It is your duty to represent your constituents. I am urging you to completely revise the Seattle budget for 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by otreanorm** [comment]
Please let me know when this is a sharable and open issue.

**Comment by mrgifted** [comment]
The mayor's name is misspelled in the last paragraph. Should be "Durkan."

**Comment by mrgifted** [comment]
Please also refer to #282 and #253.

**Comment by Ceshion** [comment]
I will add #282 and ensure the language in this reads correctly (looking at "draconian (fine?)" in the last paragraph)

**Comment by serifluous** [comment]
@otreanorm the email link is up! https://defund12.org/seattle
