### ISSUE TITLE
Please add Greensboro, NC 

### ISSUE THREAD

**Issue by Sam9712** [teddywilson/defund12.org#210]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by averymcguirt** [comment]
Please provide requested information for inclusion of your city!
