### ISSUE TITLE
Add Greensboro, NC please

### ISSUE THREAD

**Issue by tygoodlad** [teddywilson/defund12.org#213]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by averymcguirt** [comment]
If you'd like to add a city, please include the requested info!
