### ISSUE TITLE
Please add Orange County, CA to the list! OC FOLKS: PLEASE EDIT + ADD INFO 

### ISSUE THREAD

**Issue by andreashinyoung** [teddywilson/defund12.org#220]
We must defund the Orange County police and prioritize the health of our black and marginalized communities

Lisa.Bartlett@ocgov.com
Michelle.Steel@ocgov.com
Andrew.Do@ocgov.com
Donald.Wagner@ocgov.com
Donald.Wagner@ocgov.com
media@da.ocgov.com
Media@da.ocgov.com

To my government representatives, 

I am writing in deep concern for the health of OC's community. It has become more than clear that a radical shift in our concept of policing and community health must take place at the local level. It is unacceptable that black and marginalized communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors.

Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer. Moreover, this deep lack of trust that the government is breeding by terrorizing its own people, rather than safeguarding our health, is an alarming risk for future generations to live peacefully and safely with each other. 

The United States does not have a national healthcare system. Instead, we have the largest military budget and some of the most well-funded and militarized police departments in the world. While police and military funding has increased every single year since 1973, funding for public health and community outreach decreased every year, crystallized most recently when the Trump administration eliminated the US Pandemic Response Team in 2018, citing “costs”.

The time has come to defund the police.

Santa Ana Police is the 8th most violent department in the U.S., and Anaheim is the 9th. This is not what Orange County, CA stands for. From 2003-2016, Anaheim Police Department killed 33 people during the process of arrest, and nearly 40% of them were unarmed. Since 2014, the rate of arrest-related deaths caused by Anaheim PD exceeds that of LAPD, NYPD, and San Fran PD and is 74% higher than average for police in California. 

How can it be that agents funded for "public protection" are responsible for 17% of all homicides in the city (2003-2016)? In the years 2009 and 2016, 36% of all homicides were in the hands of Anaheim officers. Frankly, this is unacceptable. It is inhumane and impossible to ignore as an issue anymore. Defunding the police and finding greater 

Rather, we need a radical increase for funding towards community services and healthcare. We need youth programs, increased mental health services, neighborhood infrastructures, childcare, and community outreach for those who need these services most. We need more funds for rehabilitation and the re-entry process for formerly incarcerated individuals, and help increase employment and education rates. We need to build a society that does not need the level of policing. 

We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

We call for defunding of police and for those dollars to be rerouted to strengthen community health system. 

Sincerely,

**Comment by ctneal91** [comment]
I am taking this right now.

**Comment by ctneal91** [comment]
Doug Chaffee was missing from the Board of Supervisors, so I added the best office email I could find for him: Fourth.District@ocgov.com

**Comment by andreashinyoung** [comment]
I wasn't sure if the right county officials were included here to receive the message, and I wonder if there are more specific upcoming issues that are best to include?
