### ISSUE TITLE
Please add Milwaukee, WI

### ISSUE THREAD

**Issue by taylorwalek** [teddywilson/defund12.org#223]
Subject: Defund MPD, Reallocate for Social Equity

Cavalier.Johnson2@milwaukee.gov,
ahamil@milwaukee.gov,
nkovac@milwaukee.gov,
rjbauma@milwaukee.gov,
ald05@milwaukee.gov,
mcoggs@milwaukee.gov,
Khalif.Rainey@milwaukee.gov,
Chantia.Lewis@milwaukee.gov,
mmurph@milwaukee.gov,
mark.borkowski@milwaukee.gov,
JoseG.Perez@milwaukee.gov,
scott.spiker@milwaukee.gov,
Marina@milwaukee.gov,
russell.stamper@milwaukee.gov

Dear Milwaukee Councilmembers,  
My name is [x] and I am a resident of [NEIGHBORHOOD/CITY]. 

I am extremely concerned with the City of Milwaukee’s inordinate investment in the Milwaukee Police Department (MPD) at the expense of critical youth, education, and health services.

I am asking that the Milwaukee Common Council make a more overt and visible commitment to racial justice. I demand that the budget vote be delayed so that Council may find ways to redirect money away from Milwaukee Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office towards an ethical and equal reallocation of the city’s expenditures, away from MPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons. As such, I demand more aggressive financial support be directed to those areas.

I also urge the Milwaukee Common Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity. Justice will only be served when the police are reformed, and this will not be possible until we defund them.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns.

Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,
 [x]

**Comment by carrieham** [comment]
It's up!

**Comment by taylorwalek** [comment]
Thank you so much!!
