### ISSUE TITLE
ASAP NEED!! Minneapolis email is missing 3 City Council Member emails. Here they are 

### ISSUE THREAD

**Issue by nitemare-d** [teddywilson/defund12.org#225]
Hi,

You're missing these three emails from the Minneapolis City Council email: jeremy.schroeder@minneapolismn.gov 
andrew.johnson@minneapolismn.gov
linea.palmisano@minneapolismn.gov

I work with @MNWFPC and we just mobilized over 3k folks to email and share to dismantle mpd today and more. These three city council members are the ones that need to be flipped to support the defunding of MPD so it's extremely important that they get our bases email. I hope yall can resolve this swiftly.

Thank you (this is so dope!)

Maryama Dahir
digital@womenforpoliticalchange.org

**Comment by averymcguirt** [comment]
Adding immediately! Thank you for catching this!

**Comment by averymcguirt** [comment]
(I've closed this out now but if you don't see the updates within 10 mins or so feel free to reopen the issue!) @nitemare-d

**Comment by nitemare-d** [comment]
> Adding immediately! Thank you for catching this!

Amazing! Love what yall have set up! We are going to defund MPD today.
