### ISSUE TITLE
St. Louis, MO please!

### ISSUE THREAD

**Issue by jiv-lackson** [teddywilson/defund12.org#23]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by teddywilson** [comment]
Hey could you please fill the items in the template above and then we'll get St. Louis on there for sure!

**Comment by carrieham** [comment]
Hello!

Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!
