### ISSUE TITLE
Please add!! Nashville, TN - Oppose BL2020-286

### ISSUE THREAD

**Issue by amessarah13** [teddywilson/defund12.org#231]
**To:**
jim.shulman@nashville.gov
**cc:** bob.mendes@nashville.gov
**cc:** john.cooper@nashville.gov

**Subject:** I oppose BL2020-286

**Message:**

Hello,

My name is [YOUR NAME], and my address is [YOUR ADDRESS]. I am writing to say that I am strongly against BL2020-286.

The mayor's budget would spend $496 million on a "public safety" system that does not keep us safe. The vast majority of that money would be spent on police, jails, and courts. That means the mayor wants to spend more on cops and cages than on almost all public goods combined. This isn't how we create public safety. True public safety requires fully-funded and community-controlled resources, not more police and jails.

In the midst of a budget crisis, the mayor is proposing we increase spending on police and jails, and decrease spending on affordable housing, social services, transit, and other critical public goods. This is unacceptable and will not keep us safe. 

Overpoliced communities are not safe communities. Thriving communities are safe communities, and communities thrive when they are well-resourced. We deserve a budget that divests from policing and jails and uses that money to invest in our communities.

Sincerely,
[YOUR NAME]

**Comment by emilyhuntsman** [comment]
adding!
