### ISSUE TITLE
Please Add Broome County NY to the list

### ISSUE THREAD

**Issue by jtmny94** [teddywilson/defund12.org#237]
**Broome County Legislators:** 

stephen.flagg@broomecounty.us, scott.baker@broomecounty.us, kelly.wildoner@broomecounty.us, kim.myers@BroomeCounty.US, daniel.j.reynolds@broomecounty.us, greg.baldwin@broomecounty.us, matthew.pasquale@broomecounty.us, jason.shaw@broomecounty.us, matt.hilderbrant@broomecounty.us, cindy.obrien@broomecounty.us, susan.ryan@broomecounty.us, rick.balles@broomecounty.us, bob.weslar@broomecounty.us, mary.kaminsky@broomecounty.us, mark.whalen@broomecounty.us

SUBJECT: Commit to reallocate for social equity 

Dear Broome County Legislature,

Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking you to reallocate money away from the Broome County PD. Much scholarship shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. As such, I demand a meaningful reallocation of PD funds towards healthcare and social programs.

Sincerely, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
got it!

**Comment by jtmny94** [comment]
Thank you!
