### ISSUE TITLE
Buffalo Police Department Budget Reform and Action Plan

### ISSUE THREAD

**Issue by aschulman1** [teddywilson/defund12.org#242]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email

Buffalo Police Department Budget Reform and Action Plan

******* A list of emails (at least one) for the government officials you’d like to receive the message mayor@city-buffalo.com, jferoleto@city-buffalo.com, dpridgen@city-buffalo.com, dfranczyk@city-buffalo.com, rfontana@city-buffalo.com, uwingo@city-buffalo.com, darivera@city-buffalo.com, jgolombek@city-buffalo.com, cscanlon@city-buffalo.com, rwyatt@city-buffalo.com
******* A detailed message concerning the budgeting decisions that are at stake in your community To the Buffalo Common Council and Office of Mayor Byron Brown, 

I am [NAME] and I am a resident of [PLACE]. I am imploring you to reconsider the Buffalo Police Department's $121.9 million dollar budget immediately. Buffalo Police officers pushed a non violent 75 year old man to the ground, while he was exercising his first amendment rights. In case you have not seen the footage, it is linked below. Many of these officers were not wearing masks during a global pandemic. The net budget for police public "safety" in the budget you passed yesterday is $121,931,696. 

I am calling for these officers to be charged and removed from service, effective immediately. I am calling for Mayor Brown and the Buffalo Common Council to have an emergency meeting regarding this matter. I am asking that an action plan for sustainable, longterm change is created and upheld.  

Recreational programming for the elderly is budgeted at $1,013,519. 

The net budget for youth programs is $401,336.That is 30,281 PERCENT MORE of Buffalo taxpayer dollars spent on the police who walked past an elderly man bleeding from his head on our sidewalks than children. 30,281 PERCENT MORE resources to empower the person who pushed this man to the ground than kids who often rely on schools, now shut down due to the pandemic, to eat.

Buffalo has the nation's fourth worst poverty rate for children. Almost half of our city's children live in poverty. 

We want to know: why are the majority of taxpayer dollars in one of the country's poorest city funding a Police department that has had 15 cases of alleged police brutality or excessive force since 2006, with 13 of the victims of those 15 cases, or 86 percent, being people of color? Quentin Suttles. Wilson Morales. A former Erie County Sheriff's Deputy assaulted someone at a tailgate party and was found guilty of falsifying records. Pito Rivera. Devin Ford. Troy Hodge. Marcus Neal. Shaun Porter was brutally beaten while an inmate in handcuffs while officers Joshua Craig and Anthony D'Agostino watched and laughed. Shaun was given a $300,000 settlement by you, the Common Council. Four black teenagers Gregory Kwaiatkowski assaulted and called "savage dogs." Kwaiatowski also choked David N. Mack in 2006. Kwaiatkowski was sentenced to four months in prison in 2018 for pleading guilty in December 2016 to a civil rights violation dating back to 2009. Timothy Stanton, Jr. Jose Hernandez-Rossy (at a traffic stop). Wardel "Meech" Davis, who died in police custody. National Air Guardsman William Sager who was handcuffed while unconscious and later died after being pushed down a flight of stairs by a bar manager. John T. Willet, a Black man, was kicked and slapped while handcuffed on the ground by Buffalo Police officer John Cirulli, who was sentenced to a year of probation. Cirulli resigned and pleaded guilty to two federal misdemeanor civil rights violations earlier in 2014. 

This is unacceptable. We are calling on the Buffalo Common Council, Buffalo Police Commissioner, and Mayor Byron Brown to reduce the Buffalo Police department's budget, revise all training practices for police officers to include de-escalation and adopt Campaign Zero's #8cant wait policies, and re-allocate police funding to invest in our community--as a start. Many of these altercations involved drugs. Drug use is the product of poverty. Improving our educational system, local opportunities for economic growth, programs that fight hunger, foster neighborhood communities, and housing will combat the root of these altercations--as a start. 

How are you going to show up for a city in desperate need of help? How are  Because spending $121.9 million dollars on the Buffalo Police is not the solution. 

[YOUR NAME HERE]

Sources: 
https://www.cnn.com/2020/06/05/us/buffalo-police-suspension-shoving-man-trnd/index.html
https://www.bizjournals.com/buffalo/news/2019/01/15/buffalo-posts-the-nations-fourth-worst-poverty.html
https://buffalonews.com/2020/01/01/lagging-in-2020-buffalo-needs-to-close-gaps-to-prosper-by-2030/
https://www.wkbw.com/news/i-team/15-cases-of-alleged-police-brutality-excessive-force-in-wny-since-2006
https://www.joincampaignzero.org/

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by ctneal91** [comment]
On it

**Comment by aschulman1** [comment]
Thank you so much! There’s a typo in the last line-please delete the “how are” before “because.” Thank you! 

☆彡 @anyaschulman
