### ISSUE TITLE
Montgomery County, MD

### ISSUE THREAD

**Issue by peroty** [teddywilson/defund12.org#245]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
MD Resident for Reforming the Montgomery County Police Department
******* A list of emails (at least one) for the government officials you’d like to receive the message
marc.elrich@montgomerycountymd.gov
Councilmember.Katz@montgomerycountymd.gov
Councilmember.Hucker@montgomerycountymd.gov
councilmember.albornoz@montgomerycountymd.gov
Councilmember.Friedson@montgomerycountymd.gov
Councilmember.Glass@montgomerycountymd.gov
councilmember.jawando@montgomerycountymd.gov
Councilmember.Navarro@montgomerycountymd.gov
councilmember.Rice@montgomerycountymd.gov
Councilmember.Riemer@montgomerycountymd.gov

******* A detailed message concerning the budgeting decisions that are at stake in your community

(Don't forget to replace the [x]'s with your information!) 
My name is [your name], and I am a resident of Montgomery County, MD. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Our county has been at the forefront of much of this action.

The brutal, senseless, and violent murder of George Floyd at the hands of police officers derelict in their duties to protect and serve is deeply disturbing. We, as a nation, are in need of a drastic overhaul in policing. Systems of oppression must be undone, and reallocating much of the budget for the MPD to programs and city-led initiatives that support education, rehabilitation, public health, and community-oriented initiatives is a goal that must be achieved. 

Montgomery County's Police is not exempt from racial issues. There is story after story of black people being harassed, searched and arrested for simple being black. 

How many of you have been arrested for helping a drunk neighbor home?
What about standing outside of a McDonalds?
What about walking down the street?
Will Jawando himself was stopped for driving while black. If even elected officials are not safe from this treatment, how can the average person have any sense of safety and trust in the police?

This is not acceptable behavior for people expected to uphold the law and keep all members of the community safe. There are consequences to actions. Even if you wear a badge.

Sincerely, [your name]

**Comment by ctneal91** [comment]
On it

**Comment by peroty** [comment]
Thank you, sir. I am not the voice to be heard but I can at least get it on the list for other people to say what needs to be said.

**Comment by teddywilson** [comment]
This is great, but I think we're missing some critical information about police budgeting specifically.
