### ISSUE TITLE
email bounceback

### ISSUE THREAD

**Issue by tokimonster** [teddywilson/defund12.org#249]
councilmember.englander@lacity.org bounced back.

**Comment by serifluous** [comment]
councilmember.Lee@lacity.org replaced Englander last year.

https://en.wikipedia.org/wiki/Los_Angeles_City_Council_District_12

**Comment by ctneal91** [comment]
on it

**Comment by serifluous** [comment]
@ctneal91 seems like it's already being addressed in PR #246! Didn't notice this was already filed as an issue.
