### ISSUE TITLE
Add Seattle, WA please!

### ISSUE THREAD

**Issue by kmedlock** [teddywilson/defund12.org#253]

**Comment by EricaEggleton** [comment]
This would include:

Mayor: Jenny Durkan (@mayorjenny)

City Council members:

Lisa Herbold (lisa.herbold@seattle.gov)
Tammy J. Morales (tammy.morales@seattle.gov)
Kshama Sawant (kshama.sawant@seattle.gov)
Alex Pedersen (alex.pedersen@seattle.gov)
Debora Juarez (debora.juarez@seattle.gov)
Dan Strauss (dan.strauss@seattle.gov)
Andrew J. Lewis (andrew.lewis@seattle.gov)
Teresa Mosqueda (teresa.mosqueda@seattle.gov)
Lorena González (lorena.gonzalez@seattle.gov)
