### ISSUE TITLE
Please update NYC to include the explicit demand of defunding at least $1 billion from the NYPD

### ISSUE THREAD

**Issue by darrengoldner** [teddywilson/defund12.org#255]
Please update NYC to include the explicit demand of defunding at least $1 billion from the NYPD. We need to be firm, clear with the demand. NYC council members will otherwise take meaningless reductions and advertise them as success. Here's an example of the modified email:

full mailto
mailto:mguerra@council.nyc.gov,District2@council.nyc.gov,SpeakerJohnson@council.nyc.gov,KPowers@council.nyc.gov,BKallos@BenKallos.com,Helen@HelenRosenthal.com,District7@council.nyc.gov,DAyala@council.nyc.gov,D09perkins@council.nyc.gov,yrodriguez@council.nyc.gov,District11@council.nyc.gov,Andy.King@council.nyc.gov,MGjonaj@council.nyc.gov,fcabrera@council.nyc.gov,Rtorres@council.nyc.gov,District16Bronx@council.nyc.gov,salamanca@council.nyc.gov,RDiaz@council.nyc.gov,district19@council.nyc.gov,pkoo@council.nyc.gov,FMoya@council.nyc.gov,BGrodenchik@council.nyc.gov,RLancman@council.nyc.gov,dromm@council.nyc.gov,JVanBramer@council.nyc.gov,Adams@council.nyc.gov,Koslowitz@council.nyc.gov,District30@council.nyc.gov,drichards@council.nyc.gov,eulrich@council.nyc.gov,slevin@council.nyc.gov,areynoso@council.nyc.gov,LCumbo@council.nyc.gov,district36@council.nyc.gov,info38@council.nyc.gov,lander@council.nyc.gov,meugene@council.nyc.gov,District41@council.nyc.gov,AskJB@council.nyc.gov,AskKalman@council.nyc.gov,District45@council.nyc.gov,AMaisel@council.nyc.gov,MTreyger@council.nyc.gov,cdeutsch@council.nyc.gov,DROSE@Council.nyc.gov,SMatteo@council.nyc.gov,borelli@council.nyc.gov?subject=Commit%20to%20Vote%20No%20on%20the%20Mayor's%20Budget%20%26%20Defund%20the%20NYPD%20By%20At%20Least%20%241%20Billion&body=Dear%20New%20York%20City%20Council%20Members%2C%0D%0A%0D%0AMy%20name%20is%20%5BYOUR%20NAME%5D%20and%20I%20am%20a%20resident%20of%20%5BBOROUGH%5D.%20Last%20April%2C%20NYC%20Mayor%20Bill%20De%20Blasio%20proposed%20major%20budget%20cuts%20for%20the%20Fiscal%20Year%202021%2C%20especially%20to%20education%20and%20youth%20programs%2C%20while%20refusing%20to%20slash%20the%20NYPD%20budget%20by%20any%20significant%20margin.%0D%0A%0D%0AI%20am%20emailing%20today%20to%20demand%20that%20you%20vote%20no%20on%20the%20Mayor's%20FY21%20proposed%20budget%20and%20ONLY%20vote%20for%20a%20budget%20that%20includes%20AT%20LEAST%20%241%20billion%20in%20cuts%20to%20the%20NYPD%20with%20equal%20reallocation%20towards%20social%20services%20and%20education%20programs.%0D%0A%0D%0AMayor%20de%20Blasio%20and%20Governor%20Cuomo%20have%20doubled%20the%20presence%20of%20the%20NYPD%20on%20New%20York%20City%20streets.%20I%20am%20asking%20that%20city%20officials%20lobby%20the%20same%20amount%20of%20attention%20and%20effort%20towards%20finding%20sustainable%2C%20longterm%20change.%0D%0A%0D%0AThank%20you%2C%0D%0A%5BYOUR%20NAME%5D%0D%0A%5BYOUR%20ADDRESS%5D%0D%0A%5BYOUR%20EMAIL%5D%0D%0A%5BYOUR%20PHONE%20NUMBER%5D

subject: Commit to Vote No on the Mayor's Budget & Defund the NYPD By At Least $1 Billion
body: Dear New York City Council Members, 

My name is [YOUR NAME] and I am a resident of [BOROUGH]. Last April, NYC Mayor Bill De Blasio proposed major budget cuts for the Fiscal Year 2021, especially to education and youth programs, while refusing to slash the NYPD budget by any significant margin. 

I am emailing today to demand that you vote no on the Mayor's FY21 proposed budget and ONLY vote for a budget that includes AT LEAST $1 billion in cuts to the NYPD with equal reallocation towards social services and education programs.

Mayor de Blasio and Governor Cuomo have doubled the presence of the NYPD on New York City streets. I am asking that city officials lobby the same amount of attention and effort towards finding sustainable, longterm change. 

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
