### ISSUE TITLE
Add Charlotte, NC ASAP please (needed before June 8)

### ISSUE THREAD

**Issue by mudkipsandrainbows** [teddywilson/defund12.org#26]
Subject: Defund CMPD and Eliminate "Crowd Control" Weapons
To: mayor@charlottenc.gov,
Marcus.jones@charlottenc.gov
James.mitchell@charlottenc.gov,
Braxton.winston@charlottenc.gov,
dimple.ajmera@charlottenc.gov,
larken.egleston@charlottenc.gov,
Malcolm.graham@ci.charlotte.nc.us,
Victoria.watlington@charlottenc.gov,
Renee.johnson@charlottenc.gov,
matt.newton@charlottenc.gov,
Tariq.bokhari@charlottenc.gov,
edriggs@charlottenc.gov
Body:
Dear City Council, Mayor Vi Lyles, and City Manager Marcus Jones,

My name is [Your Name]. [Insert a little bit about what you do, who you are, and how long you’ve lived in Charlotte]. I’m writing to demand for a reduction of the Charlotte Mecklenburg Police Department’s $290.2 million budget allocation, with no additional funding of over $4 million allocated to CMPD in the 2021 budget. I am also writing to demand that the city of Charlotte abolishes CMPD’s usage of chemical weapons and rubber bullets.

In the context of nationwide protests against racist police brutality, CMPD has relentlessly stalked, manipulated, cornered, kettled, teargassed, pepper balled, and attacked the community it claims to serve. They have assaulted peaceful protesters, medics, children, and reporters with reckless abandon. On June 2, officers trapped a crowd of peaceful protesters in a parking garage with tear gas, pepper balls, and flash-bangs. A viral video of this incident has sparked outrage in North Carolina and beyond. As the Charlotte Observer wrote in its coverage of the attack, one protester stated that it felt as though their face “was melting off.” These chemical weapons, which are supposedly “non-lethal,” often result in violent injuries. Other cities have seen victims lose their eyes to rubber bullets and suffer horrific respiratory attacks from being pepper sprayed or teargassed. The usage of airborne chemical agents is particularly cruel and dangerous when considering the fact that coronavirus already weakens the respiratory and immune systems. 

Attempts to reform the Charlotte Mecklenburg Police Department have been woefully inadequate in reducing racial disparities in policing. Between 2013 and 2019 CMPD has killed Black people at 3.1 times the rate of white people -- higher than the already shameful national average. In spite of these troubling statistics and the national outcry against the murders of Keith Lamont Scott, Danquirs Franklin, and many others, CMPD continues to drag its feet on even the most basic reforms: bans on chokeholds or strangleholds, banning shooting at moving vehicles, requirements to exhaust all other means before shooting, requiring other officers to intervene if they see an officer using excessive force, and extensive reporting requirements. Its community review board serves only an advisory role, and as a result, a whole lot of community input is summarily ignored. 

The truth of the matter is that pouring 40% of our city’s budget into a bloated, militant, and punitive police force will not stop crime in our city. It will only serve to encourage broken-windows policing, criminalize Black Charlotteans and waste tax dollars. If we want to stop crime, we have to fund the measures that will prevent it: education, arts, parks, social services, services for homeless and impoverished people, and healthcare. 

Teargassing protesters and trying to spin it a week before a budget vote is not how you build trust in a city already marred by racist police violence. If anything, this reflects an outrageous disregard for our community’s safety and well-being, and the outright danger CMPD presents to the most vulnerable Charlotteans. CMPD’s platitudes, kneeling, and “community outreach” don’t fool us. It is past time to retire the use of chemical weapons and pull back funding of CMPD. 

Cities across America are reevaluating their racist policing systems, and we hope that Charlotte can be at the forefront of this movement. We will not be considered a leader for the New South if we do not interrogate racism in every way that it exists in Charlotte. 

Please do your part and implement these measures.

Best wishes,

[Your name]

Budget matters at stake: City Council will be having a vote on the 2021 budget on Monday, June 8th. The budget proposal includes an over $4 million increase in CMPD's budget, which is already 40% of the city's total budget. More information here: https://defundcmpd.github.io/

If CLT Uprising wants to submit a different email template, please defer to them. 

Solidarity!

**Comment by teddywilson** [comment]
Charlotte is live via https://github.com/teddywilson/defund12.org/commit/66f8ba3dcb03e76581aee1265818c295230872e9

Building now and should be up momentarily. Thank you for your contribution!

**Comment by mudkipsandrainbows** [comment]
Thanks so much!
