### ISSUE TITLE
Grand Rapids, MI

### ISSUE THREAD

**Issue by galenhood** [teddywilson/defund12.org#267]
Subject: Proposal for People's Budget of Grand Rapids

Elected Officials                              

Mayor Bliss
616-456-3168
mayor@grcity.us

Max Frantz
City Comptroller
616-456-3189
comptroller@grcity.us 

Jon O’Connor
First Ward Commissioner
616-456-3856
joconnor@grcity.us

Kurt Reppart
First Ward Commissioner
616-456-3578
kreppart@grcity.us

Joseph D. Jones
Second Ward Commissioner
jdjones@grcity.us

Milinda Ysasi 
Second Ward Commissioner
616-456-3859
mysasi@grcity.us

Senita Lenear
Third Ward Commissioner
515-456-3860
slenear@grcity.us

Nathaniel Moody
Third Ward Commissioner
616-456-3857
nmoody@grcity.us

Appointed Officials

Mark Washington
City Manager
616-456-3166
manager@grcity.us

Anita Hitchcock
City Attorney
616-456-4021
cityatty@grcity.us

Departments, Divisions, and Offices

Budget Office
616-456-3954
meastman@grcity.us

Office of Communications
616-456-4101
asnow@grcity.us

Office of Community Development
616-456-4619
communitydev@grcity.us

Office of Equity & Engagement
616-456-3027
inclusion@grcity.us

State Representatives

Rep. Rachel Hood (D)
517-373-0822
RachelHood@house.mi.gov

Rep. David LaGrand (D)
517-373-2668
DavidLaGrand@house.mi.gov 

Message:

I am asking you to call an emergency council meeting and challenge the mayor’s proposed budget in favor of The People’s Budget before the budget is adopted on July 1st.  I know that public services are set to be cut by $22M by FY2021 besides in business redevelopment and a proposed cut to a community engagement effort within the Grand Rapids Police Department. I think that this is unacceptable, and ask that funds be redirected away from the Grand Rapids Police Department and into public services such as housing, education, and healthcare access, and to consider direct financial relief to citizens, not just businesses, impacted by COVID-19. This funding must be allocated in a way that provides the most relief to those in our community that are the most marginalized and victimized by the structural racism and inequity that Grand Rapids is built upon, and that the Grand Rapids Police Department and your City Commission is complicit in enforcing. Public tensions are rising and public opinion is dwindling in regard to the City’s inappropriate response to the murder of George Floyd and militarized, over-policed response to subsequent protests of police brutality and racism.

**Comment by emilyhuntsman** [comment]
working on it!

**Comment by galenhood** [comment]
THANK YOU SO MUCH!!!

**Comment by abouws** [comment]
Hello, thank you for this, one of the emails bounced back due to a typo:
The v at at of gov is missing. 

[DavidLaGrand@house.mi.gov](url)

Thanks!

**Comment by serifluous** [comment]
@abouws Can you check https://defund12.org/grandrapids again and confirm? I'm seeing DavidLaGrand@house.mi.gov

**Comment by abouws** [comment]
Yes, it's correct now. The email link wasn't working so I may have missed
in my copying. Sorry about that! Thank you!

**Comment by serifluous** [comment]
@abouws Thank you!
