### ISSUE TITLE
Fort Wayne, IN

### ISSUE THREAD

**Issue by AttucksCrispus** [teddywilson/defund12.org#271]
Fort Wayne:

Email addresses: citycouncil@cityoffortwayne.org, paul@paulensley.com, russ@russjehl.com, tdidiers5@frontier.com, jasonarpcitycouncil@gmail.com, geoffreypaddock@aol.com, sharon.tucker@cityoffortwayne.org, michelle.chambers@cityoffortwayne.org, glynnhines@aol.com, freistrofferatlarge@gmail.com

Subject: Decrease funding for police in the 2021 budget

Body: Dear City Councilors,

My name is [x] and I’m a resident of Fort Wayne. I am writing about the fiscal year 2021 budget for the City of Fort Wayne.

Mayor Henry claims “It's critical for all of us to come together united with a commitment to gaining a better understanding of the divsions in our city, state, and country” yet the 2020 budget allocated $64.7 million (62% of the total general fund) to the FWPD. By contrast, Community Development received funds amounting to 5% of the total general fund, or less than a tenth of the FWPD budget.

I am asking that the Fort Wayne City Council push to make a more overt and visible commitment to the city and county’s Black and Brown communities and to combat an over-investment in their criminalization and surveillance. I therefore demand that the Council find ways to redirect money away from the FWPD’s overinflated budget. I urge you to pressure the mayor for an ethical and equal reallocation of the city’s expenditures, away from the FWPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Now especially, the City Council can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities instead—starting with education, housing, healthcare, cooperative businesses, community centers, and community-led organizations and projects.

Can I count on you to consider an alternative budget that puts a focus on social services programs?

Thank you,

[x]

**Comment by emilyhuntsman** [comment]
will submit a PR!
