### ISSUE TITLE
Columbus, Ohio

### ISSUE THREAD

**Issue by tempnametx** [teddywilson/defund12.org#28]

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Thank you!!

**Comment by jamespeacock** [comment]
I am happy to take the responsibility of creating the _layouts file for columbus. I have created an ohio branch for tackling Cleveland/Columbus/Toledo requests.

I'll monitor here for updates with the list of emails. And if they aren't posted in a day, I'll track them down

**Comment by minicreative** [comment]
Hey @jamespeacock - if you're uploading templates (recipients, subject, body, etc). you'll want to create Markdown files in the `_emails` folder. You'll have a lot of examples as a guide. The `_layouts` files aren't city-specific - I think you'll understand once you look at `_emails`. 

Thanks for your time, and follow up here if you have questions!

**Comment by jamespeacock** [comment]
Handled by #50
