### ISSUE TITLE
Elk Grove, ca 

### ISSUE THREAD

**Issue by mvgj** [teddywilson/defund12.org#280]
To: mayor and city council SteveLy@elkgrovecity.org; sdetrick@elkgrovecity.org; dsuen@elkgrovecity.org; phume@elkgrovecity.org; 
snguyen@elkgrovecity.org
Subject: Elk Grove demands a People's Budget 🔗
Message (Don't forget to replace the [x]'s with your information!) 🔗 
“I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. We demand that the City Council defund the EGPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Elk Grove residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]”

**Comment by emilyhuntsman** [comment]
working on it!
