### ISSUE TITLE
Please Add Maryland, thank you.

### ISSUE THREAD

**Issue by AsherNoor** [teddywilson/defund12.org#284]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

///

No Sir, thank YOU.
I have attached the emails and the messages as requested.
Thank you for allowing us to be a part of this.

Be safe out there.
Much Love.

[Letter_MD-Governer-and-Council.docx](https://github.com/teddywilson/defund12.org/files/4737916/Letter_MD-Governer-and-Council.docx)
[Letter_The-MD-Senators.docx](https://github.com/teddywilson/defund12.org/files/4737917/Letter_The-MD-Senators.docx)
[MD_Governor-Council_Emails.txt](https://github.com/teddywilson/defund12.org/files/4737918/MD_Governor-Council_Emails.txt)
[MD_Senators_Emails.txt](https://github.com/teddywilson/defund12.org/files/4737919/MD_Senators_Emails.txt)

**Comment by emilyhuntsman** [comment]
Working on it!
