### ISSUE TITLE
Add Newark, NJ

### ISSUE THREAD

**Issue by andrewcarter2** [teddywilson/defund12.org#293]
Email Addresses: barakara@ci.newark.nj.us, ramosa@ci.newark.nj.us, amadora@ci.newark.nj.us, gonzalezc@ci.newark.nj.us, osbornee@ci.newark.nj.us, jamesjoh@ci.newark.nj.us, mccallumjo@ci.newark.nj.us, mciverl@ci.newark.nj.us, quintanal@ci.newark.nj.us, crumpm@ci.newark.nj.us

Subject: Newark Demands Equity: Police Budget and Reform

Body: Dear Mayor Baraka and City Councilors,

My name is [NAME] and I am a resident of Newark. I urge you to redirect money away from the NPD and into social service programs that will benefit public health and our own communities. We also need to ban chokeholds, strangleholds, shooting at moving vehicles, and require police officers to practice de-escalation and comprehensive reporting ([8 Can't Wait](https://8cantwait.org/)).

Newark's 2019 Municipal Budget shows that $154,625,090 was spent on the Division of Police. This is by far the largest fraction of the city's budget, which is over double the second largest allocation of funds (Division of Fire's $72,354,451). It's an egregious statistic compared to $9,407,451 spent on the entire Department of Health and Community Wellness, $3,504,842 on the Department of Economic and Housing Development, and just $359,239 to the Division of Cultural Affairs. If this is truly representative of the council’s thoughts on how funds should be allocated in a city in which one in every 3.5 residents live in poverty ([WelfareInfo](https://www.welfareinfo.org/poverty-rate/new-jersey/newark#:~:text=The%20poverty%20rate%20in%20Newark%20is%2028.3%25.,line%20in%20the%20last%20year.)), I am ashamed to call Newark my home.

We need to ensure that the budget will be spent promoting Newark's current residents, rather than arresting, displacing, or incarcerating my neighbors. We don't need a militarized police force. Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. To fight crime we don't need more police officers. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. I am writing to insist that the upcoming budget hearings for FY 2021 reflect the voices and needs of Newark’s citizens and that changes are made to NPD's policies. Mayor Baraka and city councilors, will you look out for me and our beloved community?

Thank you,
[NAME]

**Comment by unitof** [comment]
I can do this one.

**Comment by unitof** [comment]
Anyone know if/how links are handled by email clients in mailto: URLs?

I'm gonna change the `8 Can't Wait` link to just `8cantwait.org`.

But WelfareInfo might be complicated.

**Comment by unitof** [comment]
I'll do something like a footnote.
