### ISSUE TITLE
OAKLAND, CA Email Template

### ISSUE THREAD

**Issue by stephkenna** [teddywilson/defund12.org#297]
To: atlarge@oaklandca.gov, officeofthemayor@oaklandnet.com, dkalb@oaklandca.gov, nfbas@oaklandca.gov, LMcElhaney@oaklandca.gov, district4@oaklandca.gov, Ngallo@oaklandca.gov, District6@oaklandca.gov, lreid@oaklandnet.com, ebernstein@oaklandcityattorney.org, abenson@oaklandca.gov, bjohnson@oaklandca.gov, askrcd-da@acgov.org

Subject: Oakland Resident for Defunding the OPD

Message (Don't forget to replace the [x]'s with your information!)

To Mayor Scaaf, the Oakland City Council and Oakland and Alameda County Elected Officials

My name is [YOUR NAME], and I am a resident of Oakland. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how Black people are treated in America. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

OPD has been a waste of our resources. Last year, the OPD budget was approximately half of available discretionary funds. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

I call on you to slash the OPD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our black neighbors and veterans. We implore you to give every member of our community experiencing homelessness a place to call home and the treatment they need.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,
[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by starchy** [comment]
Suggest capitalizing `Black` in `Black people`. Thanks!

**Comment by emilyhuntsman** [comment]
on the PR!

**Comment by stephkenna** [comment]
Edited original comment also. Thank you!

**Comment by underpickled** [comment]
Looks great!

**Comment by shughb** [comment]
Suggest adding people struggling with mental health in the unsheltered populations affected negatively by policing. Thanks for putting this together!
