### ISSUE TITLE
Request for Madison WI. 

### ISSUE THREAD

**Issue by gkcoleman** [teddywilson/defund12.org#302]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

Request to Re-allocate Funds from the City of Madison Police Department to Social Service Programs

district1@cityofmadison.com, district2@cityofmadison.com, district3@cityofmadison.com, district4@cityofmadison.com, district5@cityofmadison.com, district6@cityofmadison.com, district7@cityofmadison.com, district8@cityofmadison.com, district9@cityofmadison.com, district10@cityofmadison.com, district11@cityofmadison.com, district12@cityofmadison.com, district13@cityofmadison.com, district14@cityofmadison.com, district15@cityofmadison.com, district16@cityofmadison.com, district17@cityofmadison.com, district18@cityofmadison.com, district19@cityofmadison.com, district20@cityofmadison.com, allalders@cityofmadison.com

Dear Madison Council Members and Alderpersons,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am extremely concerned with the City of Madison's inordinate investment in the Madison Police Department (MPD) at the expense of critical youth, education, and health services.

I am asking that the Madison Common Council make a more overt and visible commitment to racial justice. I demand that the budget vote be delayed so that Council may find ways to redirect money away from Madison Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office towards an ethical and equal reallocation of the city’s expenditures, away from MPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons. As such, I demand more aggressive financial support be directed to those areas.

I also urge the Madison Common Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity. Justice will only be served when the police are reformed, and this will not be possible until we defund them.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns.

Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
will submit!

**Comment by gkcoleman** [comment]
Thank you!

**Comment by ArielHF6** [comment]
Thanks so much! I just sent this email and the allalders email account bounced back fyi

**Comment by emilyhuntsman** [comment]
@ArielHF6 I have removed that email from the template, feel free to comment if you find a better one that won't bounce and I can add it!

**Comment by unitof** [comment]
Yo, welcome to GitHub @emilyhuntsman! Congrats on kicking like 10 PRs in a row in your first month here!

**Comment by emilyhuntsman** [comment]
thanks @unitof! I had to teach myself how to use github to help out on this one lol
