### ISSUE TITLE
Former LA City Council Member Mitchell Englander is on the email template for Los Angeles but his email does not work and he is no longer a council member. 

### ISSUE THREAD

**Issue by Ingmarfris** [teddywilson/defund12.org#310]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by teddywilson** [comment]
I'll leave it to @emilyhuntsman to follow through on this one (thanks emily!), and I'll close out the issue for now.
