### ISSUE TITLE
Update text for Kalamazoo, MI to include new demands

### ISSUE THREAD

**Issue by erinb223** [teddywilson/defund12.org#313]
*******Subject line and email list should remain the same
******* New email body, in full:
“Hi, my name is [YOUR NAME] and I live at [YOUR ADDRESS, YOUR CITY, YOUR COUNTY]. I’m writing to let you know that I think that Kalamazoo Department of Public Safety’s use of chemical agents on peaceful protesters in late May and early June, including youth, constituted excessive force. I also think that the curfew and the presence of the National Guard in our city on June 2 did more to harm and scare us than it did to keep us safe. 

This kind of behavior is a long standing pattern with KDPS, a police force with multiple questionable in custody deaths, excessive force accusations, a documented habit of pulling over predominantly black drivers, and enough unnecessary lethal equipment to outfit a small army. The time for hiding behind canned apologies, promises of diversity training and “community policing” is over. It’s time to reduce police spending and reallocate those funds to programs that have real tangible benefits, especially to communities harmed by decades of over-policing and discrimination.

Kalamazoo Public Safety takes up 48% of the entire general fund budget for 2020. Other public services account for a paltry 8% and parks and recreation a depressing 4% of budget. That is outrageous and needs to change. Kalamazoo needs dollars for services that actually improve and lift up our community. Dollars for education, for food assistance, for housing, for people. Not policing. 

Additionally, I want to see the following actions taken by KDPS and the City Commission to hold them accountable for their violence toward our community:
IMMEDIATELY: 
KDPS will cease the use of tear gas or other chemical weapons
KDPS will cease the use of riot gear or other provocative dress when interacting with the public
KDPS will wear body cams at all times, always on and unobstructed
The Kalamazoo City Commission will order an independent investigation into KDPS response to public protests beginning May 30
KDPS will provide a weekly public briefing on the progress of their own investigations into police conduct related to public protests beginning May 30
WITHIN 2 WEEKS:
KDPS will develop and ongoing plan for quarterly reporting, to the public, of all complaints against the department or its officers, and the resolution of each
WITHIN 3 MONTHS:
ALL KDPS officers who interact with the public will have participated in racial healing circle with members of the community, led by trained facilitators
KDPS will adopt a policy requiring its officers live within the boundaries of the area the department serves

Please keep my interests in mind as you continue to discuss these matters and work toward justice in our community.

Sincerely,

[YOUR NAME]

**Comment by teddywilson** [comment]
Hey!

Would you mind editing the file directly and making a pull request with us. I'm not sure it'd necessary be right to override the entire body text, but if you'd like to made specific edits those would definitely be welcome!

https://github.com/teddywilson/defund12.org/edit/gh-pages/_emails/kalamazooMi.md

I'm going to close out the issue for now, but definitely open up a PR!

**Comment by erinb223** [comment]
Will do, thank you for letting me know!!

I have 0 idea how to GitHub (non-tech community organizer here) but I will try to figure it out.

THANK YOU for this project. SO necessary. You rock.

In Solidarity, 

Erin Bensinger (she/her)

**Comment by Ceshion** [comment]
@erinb223 is the original requestor and the updated text comes from a Kalamazoo-local black-led justice organization. all things considered, I think overwriting this is fine-- could this please be re-opened?
