### ISSUE TITLE
Please Add Vallejo, CA!

### ISSUE THREAD

**Issue by ashrelliott** [teddywilson/defund12.org#318]
Subject: Vallejo Resident for Defunding the VPD
To: michelle.straub@cityofvallejo.net, Bob.Sampayan@cityofvallejo.net, Hermie.Sunga@cityofvallejo.net, hakeem.brown@cityofvallejo.net, Pippin.Dew@cityofvallejo.net, Robert.McConnell@cityofvallejo.net, Katy.Miessner@cityofvallejo.net, Rozzana.Verder-Aliga@cityofvallejo.net, ehannigan@solanocounty.com, mebrown@solanocounty.com

To City Manager Greg Nyhoff, the Vallejo City Council and Oakland, and Solano County Elected Officials,

My name is [YOUR NAME], and I am a resident of Vallejo. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Our city has a shameful history of police abuses and murders. We are 3rd in the state per capita for police murders, and our city police have one of the highest salaries and benefits packages in the state. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

VPD has been a massive waste of our resources. Vallejo has been in the news several times over the last two years alone for acts of excessive force and murder by the police. As of June 13th last year, the city had 35 pending claims and lawsuits in connection with the Vallejo Police Department, 16 of which allege excessive force. We have one of the highest amounts of lawsuit payouts in the Bay Area, having paid out more than $7 million in civil rights lawsuit settlements involving our police department since 2011. This year, the VPD budget is approximately 22% of available city-wide spending. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

I call on you to slash the VPD budget and instead use those resources specifically towards solving homelessness, which is felt most by our Black neighbors and veterans. We implore you to give every member of our community experiencing homelessness a place to call home and the treatment they need. 

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,
[YOUR NAME]
Thank you!!

**Comment by skot** [comment]
Should we add a bit about the new police station? The City just bought VPD a $13.4 million building and are about to dump $20 million into renovating it.

https://www.timesheraldonline.com/2019/12/05/planning-commission-approves-changes-to-zoning-for-waterfront-building/

**Comment by skot** [comment]
City Manager Greg Nyhoff's email is `greg.nyhoff@cityofvallejo.net`

**Comment by ashrelliott** [comment]
Yes, please! I meant to add it in there, but ran out of time on my lunch break to do the research on it. 
    On Friday, June 5, 2020, 03:47:37 PM PDT, Skot Croshere <notifications@github.com> wrote:  
 
 


Should we add a bit about the new police station? The City just bought VPD a $13.4 million building and are about to dump $20 million into renovating it.

https://www.timesheraldonline.com/2019/12/05/planning-commission-approves-changes-to-zoning-for-waterfront-building/
