### ISSUE TITLE
Indianapolis, IN, and Bloomington, IN

### ISSUE THREAD

**Issue by moriartyparty** [teddywilson/defund12.org#32]
I have email subject line, templates, and email addresses ready to go, but not sure what to do next.

**Comment by moriartyparty** [comment]
Indy: 

Email addresses: Vop.Osili@indy.gov, Zach@adamsonforindy.com, leroy.robinson@indy.gov, Keith.Potts@indy.gov, Dan.Boots@indy.gov, Ethan.Evans2@indy.gov, Ali.Brown@indy.gov, crista.carlino@indy.gov, John.Barth@indy.gov, monroe.gray@indy.gov, william.oliver@indy.gov, maggie.lewis@indy.gov, blake.johnson@indy.gov, keith.graves@indy.gov, lakeisha.jackson@indy.gov, jessica.mccormick@indy.gov, kristin.jones@indy.gov, michael-paul.hart@indy.gov, david.ray@indy.gov, jasonhollidayccc20@gmail.com, frank.mascari@indy.gov, jared.evans@indy.gov, paul.anneed23@gmail.com, mike.dilk424@gmail.com, brian.mowery@indy.gov

Subject: Decrease funding for police in the proposed budget

Body: Dear City Councilors, 

My name is [x] and I’m a resident of Indianapolis. I am writing about the fiscal year 2021 budget for the Consolidated City of Indianapolis Marion County.

Mayor Hogsett claims to be “dedicated to investing Indianapolis’ resources back into our neighborhoods,” yet the 2020 budget allocated $253 million or 31% of the total budget to the IMPD. By contrast, Neighbourhood Services received funds amounting to 3% of the total budget, or less than a tenth of the IMPD budget. 

I am asking that the Indianapolis City Council push to make a more overt and visible commitment to the city and county’s Black and Brown communities and to combat an over-investment in their criminalization and surveillance. I therefore demand that the Council find ways to redirect money away from the IMPD’s overinflated budget. I urge you to pressure the mayor for an ethical and equal reallocation of the city’s expenditures, away from the IMPD, and towards sectors that facilitate the dismantling of racial and class inequality. 

Now especially, the City Council can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities instead—starting with education, housing, healthcare, cooperative businesses, community centers, and community-led organizations and projects.

Can I count on you to consider an alternative budget that puts a focus on social services programs? 

Thank you,

[x]





Bloomington:

Email addresses: simsji@bloomington.in.gov, volans@bloomington.in.gov, piedmoni@bloomington.in.gov, kate.rosenbarger@bloomington.in.gov, matt.flaherty@bloomington.in.gov, sue.sgambelluri@bloomington.in.gov, rollod@bloomington.in.gov, sandbers@bloomington.in.gov, ron.smith@bloomington.in.gov

Subject: Decrease funding for police in the proposed budget

Body: Dear City Councilors, 

My name is [x] and I’m a resident of Bloomington. I am writing about the fiscal year 2021 budget for the City of Bloomington.

Mayor Hamilton states that he wants to make Bloomington more “equitable” and to increase the “appeal and attractiveness of our community […] to a wide diversity of people throughout the city.”  

Despite those claims, the 2020 budget allocated $12 million, or 26% of the total budget, to the Bloomington Police department, while community services received less than $800,000, or 1.7% of the total budget.
 
I am asking that the Bloomington City Council make a more overt and visible commitment to the city’s Black and Brown communities to combat an over-investment in their criminalization and surveillance. I therefore demand that the Council find ways to redirect money away from the PPD’s overinflated budget. I urge you to pressure the mayor for an ethical and equal reallocation of the city’s expenditures, away from the BPD, and towards sectors that facilitate the dismantling of racial and class inequality. 

Now especially, the City Council can take a supportive stand on racial and social justice by significantly defunding policing and investing in the community instead—starting with housing, transportation, education, community centers, and community-led organizations and projects.

Can I count on you to consider an alternative budget that puts a focus on social services programs? 

Thank you,

[x]

**Comment by Ceshion** [comment]
I will add this template and enter a PR shortly

**Comment by moriartyparty** [comment]
Amazing! Thanks (Just to clarify--I made two templates; one for Indy, one for BTown)

**Comment by Ceshion** [comment]
my comment was worded incorrectly, I saw and added both templates 👍

**Comment by moriartyparty** [comment]
No worries. Thank you for your hard work!!!

**Comment by Ceshion** [comment]
added in #86 and #83
