### ISSUE TITLE
Add Miami, Fl

### ISSUE THREAD

**Issue by elgallo725** [teddywilson/defund12.org#33]
Hello,

Please add a template for Miami, Fl officials. Thanks!

**Comment by faelancjp** [comment]
Please add Miami!!

**Comment by Ceshion** [comment]
Following other blank requests, as contributors are handling a lot of requests - please include the following information with your request:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by faelancjp** [comment]
Thank you, I will work on this! You're doing great work. Thank you so much.

**Comment by teddywilson** [comment]
Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Thank you!!
