### ISSUE TITLE
Add Pueblo, CO

### ISSUE THREAD

**Issue by PuebloRob** [teddywilson/defund12.org#344]
To: mayor@pueblo.us, cityadmin@pueblo.us, bobschilling68@gmail.com, latencio@pueblo.us, ebrown@pueblo.us, raguilera@pueblo.us, maliff@pueblo.us, dflores@pueblo.us, lovepueblo@yahoo.com, policedept@pueblo.us

Subject: Defund Pueblo PD

Body: 
(Don't forget to replace the [x]'s with your information!)

Dear Mayor Gradisar and City Council Members,

I write to demand a reallocation of funding from Pueblo PD to social and public programming that takes place in our communities, and demand regulation to ensure oversight for public spending.

I join the calls of those across the country to Defund the Police. With record unemployment and a seemingly intractable pattern of abuse an unequal treatment by police, we need a budget that adequately and effectively meets the needs of at-risk Pueblo residents. You must support a budget that supports social equity in our community, rather than empowering the police forces that tear us apart.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Pueblo city budget for 2020-2021 fiscal year, to reflect the decades of research showing that education and social programs much better promote the safety of a city than policing.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
Working on it

**Comment by PuebloRob** [comment]
Awesome! Thank you ✊🏼 FTP
