### ISSUE TITLE
Add Columbia, MO! (City Council & Mayor)

### ISSUE THREAD

**Issue by evan-wood-very-cool** [teddywilson/defund12.org#357]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* Defund the Columbia Police Department
******* ward6@CoMo.gov, mayor@CoMo.gov, ward2@CoMo.gov, ward3@CoMo.gov, ward4@CoMo.gov, ward5@CoMo.gov, ward1@CoMo.gov
******* Hi, my name is [NAME] and I am a resident of Columbia's [YOUR COUNCIL WARD]. I am asking to redirect money away from the Columbia PD and into the public services such as housing, education, and healthcare access, and to consider direct financial relief to citizens, not just businesses, impacted by COVID-19.

As it stands, our city is facing massive revenue shortfalls due to conditions created by the Covid-19 Pandemic. Rather than see further reduction to public services and layoffs of essential public workers, I request that the mayor and city council first and foremost consider significantly defunding the police department. Police spending for the FY20 budget increased by 12%. This money can be more effectively spent in other ways to keep Columbia citizens safe.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by ratulesrar3** [comment]
PR #364
