### ISSUE TITLE
add Houston, TX please! 

### ISSUE THREAD

**Issue by ahill01** [teddywilson/defund12.org#36]
Thank u for ur service

**Comment by jamespeacock** [comment]
Can assign this one to me as well.

@ahill01  Could you post an email template here asking for defunding and/or police reform. I will handle finding the list of representatives' emails

**Comment by jamespeacock** [comment]
Finished here:
https://github.com/teddywilson/defund12.org/pull/50

**Comment by teddywilson** [comment]
Closing the issue up, and we'll take a look at the PR.

Thanks @jamespeacock !
