### ISSUE TITLE
create a template for Phoenix!!!

### ISSUE THREAD

**Issue by jforjustice** [teddywilson/defund12.org#362]
SUBJECT: Fully Fund The OAT and Civil Review Board And Redirect Additional PHX PD Funds

EMAILS: mayor.gallego@phoenix.gov, council.district.1@phoenix.gov, council.district.2@phoenix.gov, council.district.3@phoenix.gov, council.district.4@phoenix.gov, council.district.5@phoenix.gov, council.district.6@phoenix.gov, council.district.7@phoenix.gov, council.district.8@phoenix.gov

TEMPLATE: My name is [NAME] and I live in [DISTRICT OR CITY]. I am writing to you as a constituent who is disturbed by the injustices and brutality carried out by police forces across the country, and particularly in the Phoenix PD.
In February, the council approved a community review board and Office of Accountability and Transparency. They were given the power to: 
-investigate and provide independent reports on police use-of-force incidents and citizen complaints. 
-make disciplinary recommendations for individual officers to the Police chief 
-recommend policy changes based on research and community feedback.
When the council approved the plan, it anticipated it would cost about $3 million, but in Wednesday’s 2020-21 budget decision it only received $400,000.
In 2019, The Phoenix PD received $721 million from the City of Phoenix. The current City Manager recommendation is $741 million, a $20 million increase, yet they can’t provide $3 million to OAT.
Ending police brutality should be a budget priority. Justice should be a budget priority. Without oversight, there will be no consequences.
I demand that you, as a representative of the Phoenix constituents, fully fund the $3 million for the OAT, and redirect the additional $20 million for the Phoenix PD to social services and cultural programs, which are backbones of any healthy community.
Thank you.
Sincerely, [NAME] [EMAIL] [PHONE NUMBER]

**Comment by ratulesrar3** [comment]
PR #367
