### ISSUE TITLE
Please Include Detroit, MI

### ISSUE THREAD

**Issue by tegarcia12** [teddywilson/defund12.org#365]
I would like to email the Detroit City Clerk, as I cannot find emails for the Mayor’s office or Detroit Police Dept online (if someone else is able to find them, any insight is appreciated). Find the clerk’s email below: 

CityClerkHelpDesk@detroitmi.gov

Detroit’s police department must be defunded because of the city’s desperate need for funding in more crucial areas of public services. The Detroit Public Schools Community District is one of the most poorly funded and poorly performing school districts in the nation, with its lack of resources at the heart of its problems. The Detroit area is also facing a crisis of water shutoffs in homes because the exorbitant costs of the city’s current water system aren’r feasible for most of its residents to pay.

**Comment by teddywilson** [comment]
I would love to get Detroit on defund12.org. Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!
