### ISSUE TITLE
Please add Everett WA district 21

### ISSUE THREAD

**Issue by arielmotag** [teddywilson/defund12.org#370]
Sen Marco Liias - marko.liias@leg.wa.gov
Rep Peterson Strom - strom.peterskn@leg.wa.gov
Rep Lillian Ortiz-Self - Lillian.ortiz-self@leg.wa.gov

**Comment by teddywilson** [comment]
Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!
