### ISSUE TITLE
Ann Arbor, MI

### ISSUE THREAD

**Issue by kkshafer** [teddywilson/defund12.org#383]
******* Defund AAPD
******* CityCouncil@a2gov.org
******* 
Mayor Taylor and City Council members,

Given the history of policing and the most recent murders of Black people, the Community must have a chance to make their case to redistribute the Ann Arbor budget to prioritize services that help strengthen our communities especially during a pandemic, not more police to tear them apart.

We want a budget that reflects our priorities and needs. Historically, the city government has spent almost 30% of its funding on police. We want that funding redistributed to services that actually help Ann Arbor folks, including affordable housing, more mental health services, and rent suspension and forgiveness for those who are currently unemployed.

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.

Thank you,
[your name]
[include your phone number/address]

**Comment by emilyhuntsman** [comment]
will work on this
