### ISSUE TITLE
Boston FY21 Budget - ways and means comments

### ISSUE THREAD

**Issue by boston12345** [teddywilson/defund12.org#385]
To: ccc.wm@boston.gov

Subject: Boston FY21 Budget, Defund police and invest in funding for public health and prevention 

The City of Boston must reduce the Boston Police Department budget. The City Council needs to address a lack of investment in predominantly Black and Brown communities and an over-investment in their criminalization and surveillance including spending on the Boston Regional Intelligence Center (BRIC). 

The City Council is considering a grant of $850,000 from the Executive of Public Safety to spend on the BRIC, in addition to $4 million in the City Budget and other federal funding from Trump’s Department of Homeland Security. The City Council should not authorize the grant and should cut the BRIC line item from our city budget. BRIC manages the racist gang database and invasive surveillance that disproportionately targets Black and Brown residents. 

Now especially, the City Council can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities - starting with cutting the least transparent and most harmful parts of the BPD budget. 

Racist police violence doesn’t just happen in other cities - it happens here in Boston too. The City Council must stop investing in targeted criminalization and surveillance, and fund what Black and Brown communities need to be safe and healthy: COVID19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects. I urge you to adopt the proposals of Councilmembers Wu and Campbell. The council must adopt Budge policies in line with the #8cantwait campaign and cannot stop there. You must invest invest in policies that support all of our communities, especially communities of color that have been over policed and subject to police harassment and violence. 

Thank you, 
[name and zip]

**Comment by ctneal91** [comment]
on it now

**Comment by ctneal91** [comment]
actually just going to edit the current Boston letter to include the city ways and means committee

**Comment by ctneal91** [comment]
also adding city.council@boston.gov as well
