### ISSUE TITLE
Toledo, OH

### ISSUE THREAD

**Issue by username4627196543** [teddywilson/defund12.org#4]

**Comment by minicreative** [comment]
Hello! We'd love to add Toledo - if possible, could you please provide us with the emails of the government officials you'd like to contact, and a message that's relevant to the budget decisions that are at stake in your community? Thank you!

**Comment by cstrouse** [comment]
President of Council - Matt Cherry- Matt.Cherry@toledo.oh.gov

COUNCIL MEMBERS BY DISTRICT
District 1: Tyrone Riley - Tyrone.Riley@toledo.oh.gov
District 2:  Matt Cherry - Matt.Cherry@toledo.oh.gov 
District 3: Theresa Gadus -Theresa.Gadus@toledo.oh.gov
District 4: Yvonne Harper - Yvonne.Harper@toledo.oh.gov 
District 5: Sam Melden - Sam.Melden@toledo.oh.gov
District 6:  Chris Delaney - Chris.Delaney@toledo.oh.gov

AT-LARGE COUNCIL MEMBERS
Cecelia Adams - Cecelia.Adams@toledo.oh.gov
Gary Johnson - Gary.Johnson@toledo.oh.gov
Nick Komives -  Nick.komives@toledo.oh.gov
Rob Ludeman - Rob.Ludeman@toledo.oh.gov
Katie Moline - Katie.Moline@toledo.oh.gov
Larry Sykes - Larry.Sykes@toledo.oh.gov


Clerk of Council, Gerald Dendinger, Gerald.Dendinger@toledo.oh.gov
Asst. Clerk of Council, Julie Gibbons, Julie.Gibbons@toledo.oh.gov

**Comment by averymcguirt** [comment]
Closing this since we haven't received template.
