### ISSUE TITLE
REVISION | Georgia - Letter to Atlanta Financial Division 

### ISSUE THREAD

**Issue by kitou2422** [teddywilson/defund12.org#400]
*NOTE*
All percentages are based on the change in funding from the general fund between 2020 and 2021. I encourage you to interpret the numbers for yourself in the budget proposal for 2021: https://www.atlantaga.gov/home/showdocument?id=46291

To:
ebell@atlantaga.gov (Chief)
sagabriel@atlantaga.gov (Director Budget Administration)

Subject:
Please decrease Atlanta's Police Department’s budget

Message:
Hello, my name is [NAME] and I am a resident of [NEIGHBORHOOD]. I am asking to redirect money away from the Atlanta PD. I have noticed that in the 2021 budget proposal, from the general fund, the police department is receiving a 5.90% increase from 2020. Meanwhile, many other services are receiving cuts to their budgets. In light of recent events, I believe it is critical that the police department be reformed and its budget reduced. Money is power, and the Atlanta Police Department has an excessive amount of it. I am asking for the budget the Atlanta Police Department is receiving to be redirected into the following social services: [Department of Law (5.05% budget reduction), Department of Corrections (6.08% budget reduction), Education, Parks & Recreation, Human Resources (9.94% budget reduction)]. These departments are receiving large budget cuts not only from the general fund, but from other funds as well. I request that an emergency meeting be called before the fiscal year goes into effect in order to deny the mayor’s proposed budget and reallocate these funds to resources the citizens can benefit from.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
Thank you for your suggestions. I will incorporate some of these numbers into the current Atlanta letter. However we will NOT be advocating for funds to departments of correction, and are generally avoiding highly individualized preferences in spending.
