### ISSUE TITLE
Richmond Resident for Defunding the RPD link

### ISSUE THREAD

**Issue by AuroraBorealis925** [teddywilson/defund12.org#402]
TO: 
TOM.BUTT@intres.com
Belinda_Brown@ci.richmond.ca.us
natbates@comcast.net
eduardo_martinez@ci.richmond.ca.us
trina_jackson@ci.richmond.ca.us
jael_myrick@ci.richmond.ca.us
ben_choi@ci.richmond.ca.us
melvin_willis@ci.richmond.ca.us
demnlus_johnson@ci.richmond.ca.us
CPRC@ci.richmond.ca.us

SUBJECT: 
Richmond Resident for Defunding the RPD 🔗

To Mayor Butt, the Richmond Board of Supervisors, and Richmond Elected Officers

My name is [YOUR NAME], and I am a resident of Richmond. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

RPD has been a waste of our resources. Last year, the RPD budget was $74,990,406, the majority of which comes from the Richmond general fund. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

I call on you to slash the RPD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our black neighbors and veterans. We implore you to give every member of our community experiencing homelessness a place to call home and the treatment they need.

We can be a beacon for other cities to follow if only we have the courage to change.

Also, save Point Molate! 

Sincerely,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
We would love to add Richmond! Thank you for your submission. I'll work on getting this up shortly.

**Comment by teddywilson** [comment]
Added via: https://github.com/teddywilson/defund12.org/commit/433e8dca8d294afc734f2191051cbed889eadbd8
