### ISSUE TITLE
Georgia - Letter to representatives asking to abolish qualified immunity

### ISSUE THREAD

**Issue by kitou2422** [teddywilson/defund12.org#405]
Link to contact Congressmen in Georgia:
https://docs.google.com/document/d/1Y9lD3051A1ZjusfIc18uVUFQCVz1_37mh3MDH3ct_1s/edit?usp=sharing

Each representative has their own website you must navigate in order to contact them. You must live in the district they represent in order to send a message.

Message:
Hello, my name is [NAME] and I am a resident of [NEIGHBORHOOD]. I am asking for your support for the bill proposed by Congressman Justin Amash and Congresswoman Ayanna Pressley to end qualified immunity. This law too often allows the police and other government officials to evade justice when they have violated the rights of Americans. Its removal is essential to protect the rights of Americans. Recent events have demonstrated to me that it is necessary for our government to take radical steps to reform our police department who abuse their position of power.

Thank you for your time,
[YOUR NAME]

**Comment by averymcguirt** [comment]
Thanks for your suggestion--this is an important ask and I'm glad it has gained traction. We are here focused on local (city and county) governments, and the specific goal of defunding.
