### ISSUE TITLE
Santa Barbara, CA

### ISSUE THREAD

**Issue by emplums** [teddywilson/defund12.org#407]
A budget for the community well-being of Santa Barbara

MHarmon@santabarbaraca.gov
KSneddon@santabarbaraca.gov
MJordan@santabarbaraca.gov
OGutierrez@santabarbaraca.gov
efriedman@santabarbaraca.gov
AlGutierrez@santabarbaraca.gov
cmurillo@santabarbaraca.gov

I am a resident of the [NEIGHBORHOOD] of Santa Barbara. I am writing to demand that the Santa Barbara City Council adopt a city budget that prioritizes community wellbeing and redirects funding away from the police.

In 2019, the City of Santa Barbara allocated 42 million dollars to our police system, at 32% of our total budget. This is compared to just 13 million allocated towards community development (9.2% of the budget) and of that community development budget, 1.05 million was projected to be spent on human services, which equates to just 0.07% of the city's total budget.

We demand that the City Council begin defunding the Santa Barbara Police Department and re-allocate those funds to programs that can meet the needs of our community such as community-based mental health services, substance abuse treatment services, affordable housing programs, and more. We demand a budget that reflects the actual needs of our community.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place is not serving our community and come together to dream of a better way.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]”

**Comment by averymcguirt** [comment]
Excellent, thank you for the contribution!
Adding momentarily.

**Comment by averymcguirt** [comment]
Santa Barbara live on the website. Thanks again!

**Comment by emplums** [comment]
Thank you! Let me know if you need any help with creating PRs or if there’s anything else you need :) I actually work at GitHub 😂
