### ISSUE TITLE
Austin, TX

### ISSUE THREAD

**Issue by hi-898** [teddywilson/defund12.org#41]
Please add Austin, Texas!!

**Comment by satansenpai666** [comment]
Plz add ATX

**Comment by lytxmom** [comment]
Please add Austin, TX and Round Rock, TX

**Comment by ecommerce-guy** [comment]
+1 for ATX

**Comment by Ceshion** [comment]
Following other blank requests, as contributors are handling a lot of requests - please include the following information with your request:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by hi-898** [comment]
@jamespeacock

**Comment by carrieham** [comment]
Hello!

Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!
