### ISSUE TITLE
Please add St. Louis, MO. 

### ISSUE THREAD

**Issue by JuliTaylor** [teddywilson/defund12.org#417]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community 

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).

If this information is copied from an external source *please* provide a link to the original source.

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by teddywilson** [comment]
Hey, please reopen the issue with the information listed above. We are not accepting issues that don't contain this information.
