### ISSUE TITLE
Contributing to codebase

### ISSUE THREAD

**Issue by coreybeaumont** [teddywilson/defund12.org#436]
Hi, I want to help! 

- How can I contribute to the code base?
- Are there unassigned issues that I can work on? 
- Are there issues that need help?
- Whats the criteria for a pr?

**Comment by serifluous** [comment]
@coreybeaumont Hey! Thanks for helping. There are a few issues tagged “meets-issue-requirements” and not tagged “pr-added-not-merged” that don’t yet have a PR.

You can also hop into the [Discord channel](https://discord.gg/YMxndzd). Some folks have similar questions, so it might be better to organize ourselves in there!
