### ISSUE TITLE
Denver CO Links To Wrong Person - NEEDS FIX! 

### ISSUE THREAD

**Issue by ale2x** [teddywilson/defund12.org#451]
I received this when submitting an email to the Denver CO links, she suggested submitting these directly to Mayor Hancock. Worth changing so the effort is directed at the correct people! Thanks =] 

“Hello,

Thanks for reaching out to my office with your concerns. However, I do not represent Denver in the Colorado Senate–you can find your representative and senator at leg.co.gov/findmylegislator. Additionally, the Colorado state legislature does not control this budget.

I would recommend contacting the Denver mayor's office to fight for change with regard to DPD's funding if you have not already. You can contact Mayor Hancock here: https://www.denvergov.org/content/denvergov/en/mayors-office/contact-the-mayor.html

Take care,

Jessie Danielson
State Senator
Colorado Senate District 20
303-866-4856
www.jessiedanielson.com”

**Comment by serifluous** [comment]
Closing as a duplicate issue
