### ISSUE TITLE
please add san diego 

### ISSUE THREAD

**Issue by acd619** [teddywilson/defund12.org#47]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by jpo203** [comment]
I know that the people providing this service MUST have a lot on their plate so I am trying to help in my own city/county by providing this information.

Here is a list of all San Diego City Council members on the Sandiego.gov/citycouncil website: 

barbarabry@sandiego.gov, jennifercampbell@sandiego.gov, christopherward@sandiego.gov, monicamontgomery@sandiego.gov, markkersey@sandiego.gov, chriscate@sandiego.gov, scottsherman@sandiego.gov, vivianmoreno@sandiego.gov, georgettegomez@sandiego.gov

Here is the mayor of La Mesa where Leslie Furcron was shot in the head with a "less than lethal" bullet by police: marapostathis@cityoflamesa.us

Here is the chief of police in La mesa: pdchief@cityoflamesa.us

**Comment by acd619** [comment]
Thank you!!

**Comment by teddywilson** [comment]
@acd619 can you please work on getting an email template together for San Diego, or crowdsourcing one?

**Comment by teddywilson** [comment]
Going to close the issue out in the meantime, but please, please reopen when all the info is here. We have a lot of issues on our plate, so trying to work through the ones that are ready!
