### ISSUE TITLE
Los Angeles Council Members Incomplete

### ISSUE THREAD

**Issue by aoh414** [teddywilson/defund12.org#48]
Hi, first off thank you for creating this.

I wanted to point out that some council members seem to be missing from the LA template.

11 | Mike Bonin | Councilmember.Bonin@Lacity.Org | 213-473-7011
12 | Mitchell Englander | Councilmember.Englander@Lacity.Org | 213-473-7012
13 | Mitch O’Farrell | Councilmember.Ofarrell@Lacity.Org | 213-473-7013
14 | Jose Huizar | Councilmember.Huizar@Lacity.Org | 213-473-7014
15 | Jose Buscaino | Councilmember.Buscaino@Lacity.Org | 213-473-7015

**Comment by Ceshion** [comment]
thank you, I will add these in a PR

**Comment by Ceshion** [comment]
added in #93

**Comment by robotskirts** [comment]
Mitchell Englander is no longer a council member and the email Councilmember.Englander@Lacity.Org bounces. His address should be replaced with John Lee councilmember.Lee@lacity.org

I checked the addresses against the [current LA directory](https://www.lacity.org/government/city-directory/city-directory) and everything else looks correct.
