### ISSUE TITLE
Request: Add Los Angeles

### ISSUE THREAD

**Issue by CaitlinEG** [teddywilson/defund12.org#6]

**Comment by teddywilson** [comment]
Hello! We'd love to add Los Angeles - if possible, could you please provide us with the emails of the government officials you'd like to contact, and a message that's relevant to the budget decisions that are at stake in your community? Thank you!

**Comment by emilyhuntsman** [comment]
Hi, I just opened an issue with a link I wrote to LA!

**Comment by teddywilson** [comment]
Gonna close this out since we have LA - @CaitlinEG if this one doesn't work for you, or you want to add different content for LA, please open a new issue!
