### ISSUE TITLE
Please add Salt Lake City, Utah

### ISSUE THREAD

**Issue by rhyannonjoy** [teddywilson/defund12.org#63]

**Comment by teddywilson** [comment]
Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Thank you!!
