### ISSUE TITLE
Boulder County Budget Reform

### ISSUE THREAD

**Issue by aumo1316** [teddywilson/defund12.org#65]
![image](https://user-images.githubusercontent.com/66446326/83817057-12863a00-a681-11ea-821f-2733d2dc5415.png)
![image](https://user-images.githubusercontent.com/66446326/83817085-2336b000-a681-11ea-8907-a43bfbbd4bda.png)
![image](https://user-images.githubusercontent.com/66446326/83817095-292c9100-a681-11ea-922e-f2343608f1dc.png)

![image](https://user-images.githubusercontent.com/66446326/83819387-ed94c580-a686-11ea-9334-556488da4105.png)

**Comment by aumo1316** [comment]
![image](https://user-images.githubusercontent.com/66446326/83818140-d1435980-a683-11ea-9e3b-de8df521842f.png)

**Comment by aumo1316** [comment]
brocketta@bouldercolorado.gov
friendr@bouldercolorado.gov
josephj@bouldercolorado.gov
naglem@bouldercolorado.gov
swetlika@bouldercolorado.gov
wallachm@bouldercolorado.gov
youngm@bouldercolorado.gov
WeaverS@bouldercolorado.gov
yatesb@bouldercolorado.gov
council@bouldercolorado.gov
homeownership@bouldercolorado.gov

Dear Council Members of the City of Boulder,

My name is [NAME] and I am a resident of [NEIGHBORHOOD]. I am writing to you regarding the harassment of Zayd Atkinson, a resident of Boulder and a student at Naropa University, by the Boulder Police Department. Instead of funding the harassment of Boulder residents of color, the city should fund affordable housing.

Several council members have based their campaigns on a platform that supports affordable housing for the residents of Boulder, yet no laws have changed regarding the number of unrelated people who can live together in a house. The budget for the Boulder Police Department is $37,000,000 while the budget for Housing and Human Services is less than $5,000,000. I strongly suggest that the Boulder Police Department be defunded immediately and that the money go towards creating affordable housing within city limits.

[NAME]

**Comment by teddywilson** [comment]
Thanks, bruv! closing this out via: https://github.com/teddywilson/defund12.org/commit/84c7ae19f287fc9f22c8719f7b98c1c00b8e3090

Should be live momentarily.
