### ISSUE TITLE
New Orleans, Louisiana

### ISSUE THREAD

**Issue by hplodnarmas** [teddywilson/defund12.org#67]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by teddywilson** [comment]
Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!
