### ISSUE TITLE
Add San Jose, CA!

### ISSUE THREAD

**Issue by inaleuq** [teddywilson/defund12.org#71]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by inaleuq** [comment]
To:
mayoremail@sanjoseca.gov, District1@sanjoseca.gov, District2@sanjoseca.gov, District3@sanjoseca.gov, District4@sanjoseca.gov, District5@sanjoseca.gov, District6@sanjoseca.gov, District7@sanjoseca.gov, District8@sanjoseca.gov, District9@sanjoseca.gov, District10@sanjoseca.gov

Subject: Defund the Police Department

Message:
We demand reallocation of funding from SJPD to social and public programming that takes place in our communities, demand regulation ensure oversight board for public spending. It is an outrage that 44% of the city funding goes towards the Police Department. It has seen a rise in overtime pay which, more often than not, is paid out to officers responsible for harassing the unhoused, and Black, Indigenous, people of color.

We demand that the City Council defund the SJPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk San Jose residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to completely revise the San Jose city budget for 2020-2021 fiscal year, and to fund #CareNotCops.  Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
I'm on it!
