### ISSUE TITLE
Oklahoma City, Oklahoma & Tulsa, Oklahoma

### ISSUE THREAD

**Issue by 131213121312** [teddywilson/defund12.org#74]
Please add Oklahoma City and Tulsa Oklahoma to this list.

**Comment by teddywilson** [comment]
Unfortunately this request does not meet our base criteria so we will have to close it. Please submit a new request with the following information and we will process it:

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!
