### ISSUE TITLE
SLC, UT!

### ISSUE THREAD

**Issue by c-gill1** [teddywilson/defund12.org#75]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the LAPD’s well documented history of murdering Black people. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. But instead, the Mayor has proposed an increase in funding to the SLPD, despite the fact that crime has fallen considerably during the past few months. The SLPD has seen a rise in overtime pay which, more often than not, is paid out to officers responsible for harassing the unhoused, and Black, Indigenous, people of color.

We demand that the City Council defund the SLPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Utahans during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Although City Council has avoided voting or revising Mayor Mendenhall’s draconian budget proposal, the document is back in your hands. It is your duty to represent your constituents. I am urging you to completely revise the SLC budget for 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

mayor@slc.gov

**Comment by cstrouse** [comment]
- james.rogers@slcgov.com
- andrew.johnston@slcgov.com
- chris.wharton@slcgov.com
- ana.valdemoros@slcgov.com
- darin.mano@slcgov.com
- dan.dugan@slcgov.com
- amy.fowler@slcgov.com

**Comment by cstrouse** [comment]
SLC was submitted in #63 but lacks required info.

**Comment by cstrouse** [comment]
Closed via #124
