### ISSUE TITLE
Sacramento, CA - PLEASE! 

### ISSUE THREAD

**Issue by shelbyv** [teddywilson/defund12.org#77]
Please add Sacramento, CA to the list!

**Comment by teddywilson** [comment]
Hey can you please provide the following information for us to review?

* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

**Comment by alehma10** [comment]
dgonsalves@cityofsacramento.org; sharris@cityofsacramento.org; aashby@cityofsacramento.org; mkross@cityofsacramento.org; awarren@cityofsacramento.org; sthao@cityofsacramento.org; cdshannon@cityofsacramento.org;  Shansen@cityofsacramento.org; IArgueta@cityofsacramento.org; MCThomas@cityofsacramento.org; jschenirer@cityofsacramento.org; jescobar@cityofsacramento.org; hcoy@cityofsacramento.org; eGuerra@cityofsacramento.org; aCabrera@cityofsacramento.org; rjennings@cityofsacramento.org; hadkisson@cityofsacramento.org; dmrogers@cityofsacramento.org; lcarr@cityofsacramento.org; jrcervantes@cityofsacramento.org; mbryant@cityofsacramento.org; dSteinberg@cityofsacramento.org; jburrows@cityofsacramento.org; jbytel@cityofsacramento.org; akehoe@cityofsacramento.org; mmedina@cityofsacramento.org; lmontes@cityofsacramento.org; kfrivas@cityofsacramento.org; swhyte@cityofsacramento.org; zyeates@cityofsacramento.org; cyniguez@cityofsacramento.org; daoffice@sacda.org; NevesM@sacda.org; SupervisorSerna@Saccounty.net; SupervisorKennedy@saccounty.net, susanpeters@sacc​​ounty.net; SupervisorFrost@saccounty.net; nottolid@saccounty.net; sheriff@sacsheriff.com; community@sacsheriff.com

**Comment by alehma10** [comment]
^^ city and county council, the mayor, all of his staff, DA, and sheriff

**Comment by alehma10** [comment]
To the council in charge of the allocation of funds to the Sacramento Police Department and the jails and prisons they fill, 	

My name is [your name], and I am a resident of Sacramento. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Sacramento and its government organizations are unfortunately guilty of complacency in the unfolding of system racism. 

First off, I fervently oppose the new Sacramento County jail. We should be reducing jail populations not creating more cells that need to be filled. Jails are not an appropriate or effective way to deal with mental illness, drug use, or homelessness yet that is how the county and city use them. Please stop this very reckless use of tax dollars and invest in real solutions to our problems. The councils should spend time considering other ways they can reduce jail populations and properly reintroduce folks to prevent recidivism. 

Call an emergency joint meeting of the City Council and County Board of Supervisors to address the response by law enforcement to the George Floyd protests. The police are responding to protesters with unneeded violence, their rubber bullets are causing destruction to bodies and businesses. You all are supposed to hold Sacramento Police Department and the Sheriff’s Department accountable. Make them come up with a plan to end police-initiated violence specifically regarding the protests and into the future. 

Please call budget meetings to begin the process of reducing spending on police and sheriff by 30% and to develop funding reduction strategies for the following 4 years. The Sacramento Police Department propagates inequality in our city. Many Black and brown Sacramento residents have stories of police harassment. The police are most violent when it comes to our most vulnerable populations: trans folks and the homeless. Systems of oppression must be undone, and reallocating much of the budget for the Sac PD to programs and city-led initiatives that support education, rehabilitation, public health, and community-oriented initiatives is a goal that must be achieved. None of the CARES federal stimulus funds should not be spent on any law enforcement function, it should go towards providing housing and public health initiatives. 

Moving forward, please refuse political contributions from law enforcement unions. You are supposed to work for the people of Sacramento. We can not achieve the the drastic overhaul in policing while your hands are in their pockets. 

Lastly, please come together to elect a new District Attorney and Sheriff who are committed to racial justice, to ending mass incarceration and to stopping the killing of Black People. The current leaders have failed Black and brown communities many times in the past and it's time for a change. 

I implore you to reconsider the budget and begin working to decolonize the police. We need leaders that are transparent and work to listen to our Black and brown communities. We are overdue for change. We need reconciliation, reinvestment, and visionary leadership that creates transformational budgets and policy outcomes to save and protect Black lives. 

Thank you for your time, 
[your name]

**Comment by alehma10** [comment]
@shelbyv feel free to change anything, just threw this together borrowing lang from some of the other templetes

**Comment by serifluous** [comment]
Some of this info could be added to the existing Sacramento template

**Comment by ctneal91** [comment]
I will add to the existing sacramento template
