### ISSUE TITLE
Add Chicago, IL please! 

### ISSUE THREAD

**Issue by hmmurphy1992** [teddywilson/defund12.org#78]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by teddywilson** [comment]
Hey can you please provide the information listed above?

**Comment by cstrouse** [comment]
- Daniel La Spata, info@the1stward.com
- Brian Hopkins, ward02@cityofchicago.org
- Pat Dowell, ward03@cityofchicago.org
- Sophia King, ward04@cityofchicago.org
- Leslie Hairston, ward05@cityofchicago.org
- Roderick Sawyer, ward06@cityofchicago.org
- Gregory Mitchell, ward07@cityofchicago.org
- Michelle Harris, ward08@cityofchicago.org
- Anthony Beale, Ward09@cityofchicago.org
- Susan Sadlowski Garza, ward10@cityofchicago.org
- Patrick Thompson, ward11@cityofchicago.org
- George A. Cardenas, ward12@cityofchicago.org
- Marty Quinn, ward13@cityofchicago.org
- Ed Burke, ward14@cityofchicago.org
- Raymond Lopez, ward15@cityofchicago.org
- Stephanie D. Coleman, info@16thWard.org, ward16@cityofchicago.org
- David Moore, ward17@cityofchicago.org
- Derrick Curtis, ward18@cityofchicago.org
- Matthew O’Shea, ward19@cityofchicago.org
- Jeanette B. Taylor, none listed but probably ward20@cityofchicago.org
- Howard Brookins Jr., ward21@cityofchicago.org
- Michael D. Rodriguez, ward22@cityofchicago.org
- Silvana Tabares, ward23@cityofchicago.org
- Michael Scott Jr., ward24@cityofchicago.org
- Byron Sigcho Lopez, none listed but probably ward25@cityofchicago.org
- Roberto Maldonado, ward26@cityofchicago.org
- Walter Burnett, Jr., ward27@cityofchicago.org
- Jason Ervin, ward28@cityofchicago.org
- Chris Taliaferro, Ward29@cityofchicago.org
- Ariel E. Reboyras, ward30@cityofchicago.org
- Felix Cardona, Jr., none listed but probably ward31@cityofchicago.org
- Scott Waguespack, info@ward32.org
- Rossana Rodriguez Sanchez, none listed but probably ward33@cityofchicago.org
- Carrie Austin, ward34@cityofchicago.org
- Carlos Ramirez-Rosa, ward35@cityofchicago.org
- Gilbert Villegas, ward36@cityofchicago.org
- Emma Mitts, ward37@cityofchicago.org
- Nicholas Sposato, info@aldermansposato.com
- Samantha Nugent, none listed but probably ward39@cityofchicago.org
- Andre Vasquez, Jr., info@40thward.org
- Anthony Napolitano, ward41@cityofchicago.org
- Brendan Reilly, ward42@cityofchicago.org
- Michele Smith, Yourvoice@ward43.org
- Thomas M. Tunney, ward44@cityofchicago.org
- James M. Gardiner, ward45@cityofchicago.org
- James Cappleman, ward46@cityofchicago.org
- Matthew J. Martin, info@aldermanmartin.com
- Harry Osterman, ward48@cityofchicago.org
- Maria E. Hadden, Office@49thWard.org
- Debra Silverstein, ward50@cityofchicago.org

**Comment by teddywilson** [comment]
We just launched defund12.org/chicago. Let us know if you want anything else added, but for now I'll close this out.
