### ISSUE TITLE
Add Dallas, Texas please!

### ISSUE THREAD

**Issue by agggg** [teddywilson/defund12.org#79]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by teddywilson** [comment]
Hey can you please provide the information listed above?

**Comment by agggg** [comment]
Subject: Defund the Dallas Police Department

List of Emails: 
eric.johnson@dallascityhall.com adam.medrano@dallascityhall.com,casey.thomas@dallascityhall.com,Chad.West@dallascityhall.com,adam.mcgough@dallascityhall.com,carolyn.kingarnold@dallascityhall.com,jaime.resendez@dallascityhall.com,omar.narvaez@dallascityhall.com,adam.bazaldua@dallascityhall.com,tennell.atkins@dallascityhall.com,paula.blackmon@dallascityhall.com,lee.kleinman@dallascityhall.com,cara.mendelsohn@dallascityhall.com,jennifer.gates@dallascityhall.com,david.blewett@dallascityhall.com

Text:
Hello,

My name is [        ]. I am a resident of Dallas, Texas and I am emailing today to demand a complete overhaul on our Dallas Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our city.

The militarized tactics that our Police Department have used against its citizens in response to peaceful protesting is unacceptable and unwarranted. To ensure your dedication to our city and citizens, I demand that you defund the Dallas Police Department and start providing more support and funding towards our community efforts and organizations that serve our predominantly Latinx and Black communities, as these are the communities that are being targeted the most. By doing so, I believe this will prevent further police brutality and violence in the future.

The Dallas Police Department said that “(they) are dedicated to serving the people of Dallas and strives to reduce crime and provide a safe city.” If this true, we demand you listen to our concerns and implement change immediately.

Sincerely,
[NAME]

**Comment by jamespeacock** [comment]
handled with #50
