### ISSUE TITLE
Brownsville

### ISSUE THREAD

**Issue by yukamaria** [teddywilson/defund12.org#8]
How can I make one of these for Brownsville Texas?

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

**Comment by averymcguirt** [comment]
Closing this issue. Please reopen if you'd like to add email addresses and a template email @yukamaria
