### ISSUE TITLE
Add Seattle, please! 

### ISSUE THREAD

**Issue by apa1102** [teddywilson/defund12.org#80]

**Comment by cstrouse** [comment]
- Lorena Gonzalez (Council President), Lorena.Gonzalez@seattle.gov
- Lisa Herbold (Councilmember), Lisa.Herbold@seattle.gov
- Debora Juarez (Councilmember), Debora.Juarez@seattle.gov
- Andrew J. Lewis (Councilmember), Andrew.Lewis@seattle.gov
- Tammy J. Morales (Councilmember), Tammy.Morales@seattle.gov
- Teresa Mosqueda (Councilmember), Teresa.Mosqueda@seattle.gov
- Alex Pederson (Councilmember), Alex.Pedersen@seattle.gov
- Kshama Sawant (Councilmember), Kshama.Sawant@seattle.gov
- Dan Strauss (Councilmember), Dan.Strauss@seattle.gov

**Comment by teddywilson** [comment]
Thanks for providing the recipients @cstrouse but we will need the email template and subject as well. Closing this out for now, but feel free to reopen once this is ready!
