### ISSUE TITLE
Please Add Nassau County and Suffolk County Long Island, NY to the list 

### ISSUE THREAD

**Issue by jtmny94** [teddywilson/defund12.org#81]
Nassau County Legislators: 

rnicolello@nassaucountyny.gov, hkopel@nassaucountyny.gov, denise.ford@nassaucountyny.gov, 
kabrahams@nassaucountyny.gov, csolages@nassaucountyny.gov, vmuscarella@nassaucountyny.gov, adrucker@nassaucountyny.gov, rmwalker@nassaucountyny.gov, 

Suffolk County Legislators: 

al.Krupski@suffolkcountyny.gov, robert.Calarco@suffolkcountyny.gov, robert.Trotta@suffolkcountyny.gov, Bridget.Fleming@suffolkcountyny.gov, Anthony.Piccirillo@suffolkcountyny.gov, Kevin.McCaffrey@suffolkcountyny.gov, Rudy.Sunderman@suffolkcountyny.gov, Samuel.Gonzalez@suffolkcountyny.gov, Jason.Richberg@suffolkcountyny.gov, Tom.Muratore@suffolkcountyny.gov, Tom.Cilmi@suffolkcountyny.gov, Susan.Berland@suffolkcountyny.gov, Kara.Hahn@suffolkcountyny.gov, Steven.Flotteron@suffolkcountyny.gov, Tom.Donnelly@suffolkcountyny.gov, Sarah.Anker@suffolkcountyny.gov, Leslie.Kennedy@suffolkcountyny.gov, Leslie.Kennedy@suffolkcountyny.gov

Dear [Nassau County Legislature/Suffolk County Legislature],

Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking to redirect money away from the [Nassau County/Suffolk County] PD. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
Thank you for your submission!

**Comment by jtmny94** [comment]
Thank you so much!
