### ISSUE TITLE
Letter for Manchester, NH

### ISSUE THREAD

**Issue by abigailpowers** [teddywilson/defund12.org#84]
We are currently handling a lot of requests - please include the following information with your request: 
* Subject: Reduce the Manchester Police Department Budget
* Email address: mayor@manchesternh.gov
* Message: 

Hello, 

I am a resident of [YOUR DISTRICT]. I am writing to demand that the Manchester Board of Mayor and Alderman adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

Our country, state, and city are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

We are in the midst of a pandemic with severe economic consequences. As of April 2020, the unemployment rate in Hillsborough county has skyrocketed, and we can expect 42% lasting unemployment. Over 50% of Manchester residents are renters. When people are unemployed, they cannot pay rent; economic insecurity and housing uncertainty are sure to increase as a result of the COVID-19 pandemic.

Supporting communities in need is necessary now, more than ever. Yet the FY 2021 Budget would support the hiring of additional officers to the Manchester Police Department. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).  As such, I demand more aggressive financial support be directed to those areas, particularly in response to the economic impact of COVID-19. 

Do not forget our poor communities and communities of color who are disproportionate targets of police violence and disproportionately affected by the COVID-19 pandemic. Justice will only be served when the police are reformed, and our communities receive more support. This will not be possible until we defund them and commit to empowering our community.

We demand that the Board of Mayer and Alderman defund the Manchester Police Department. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Manchester residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to completely revise the proposed budget for the 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by cstrouse** [comment]
You may want to add the alderman. Not my community so not my call but here they are:

- kcavanaugh@manchesternh.gov
- wstewart@manchesternh.gov
- long55@comcast.net
- jroy2@manchesternh.gov
- asapienza@manchesternh.gov
- elizabethannmoreau@gmail.com
- rterrio@manchesternh.gov
- mporter@manchesternh.gov
- bshaw@manchesternh.gov
- bbarry@manchesternh.gov
- ngamache@manchesternh.gov
- khirschmann@manchesternh.gov
- jrwaa2@aol.com
- doneil@manchesternh.gov

**Comment by abigailpowers** [comment]
Oh wow! Thank you so much! For some reason I was having trouble finding their email addresses! This is great

**Comment by cstrouse** [comment]
They were hidden in a PDF.

**Comment by Ceshion** [comment]
I'll begin adding this template!

**Comment by Ceshion** [comment]
added in #152
