### ISSUE TITLE
Portland, OR

### ISSUE THREAD

**Issue by rmanro** [teddywilson/defund12.org#85]
Portland, OR
Thanks!

**Comment by cstrouse** [comment]
- Ted Wheeler, mayorwheeler@portlandoregon.gov
- Mary Hull Caballero, AuditorHullCaballero@portlandoregon.gov
- Toni Anderson (Council Clerk/Contracts), Toni.Anderson@portlandoregon.gov
- Independent Police Review, ipr@portlandoregon.gov
- Andrew Bryans (Management Services),  Andrew.Bryans@portlandoregon.gov
- Amanda Fritz (commissioner), Amanda@portlandoregon.gov
- Jo Ann Hardesty (commissioner), JoAnn@portlandoregon.gov
- Chloe Eudaly (commissioner), chloe@portlandoregon.gov
