### ISSUE TITLE
Los Angeles - letter to Garcetti and the city council

### ISSUE THREAD

**Issue by emilyhuntsman** [teddywilson/defund12.org#9]
https://tinyurl.com/EmailPeoplesBudgetLA

Will take you to a pre-written email addressed to Mayor Garcetti and all active city council members. You simply have to put in your name and district.

**Comment by emilyhuntsman** [comment]
Also, it seems like lots of people are wanting to add their towns. I would love to help by reviewing emails and creating links! I wrote a script that makes it super easy and have been using it to help a lot of people I know get their pre-written emails up and running. Just let me know!

**Comment by teddywilson** [comment]
Sounds great! As a first step I'm going to add LA, I'll close this issue out when it's live. If you want to contribute to the repository in any other ways, open up a PR and let's get it rolling!

**Comment by teddywilson** [comment]
LA is live via: https://github.com/teddywilson/defund12.org/commit/3e14c45005cb55ff47b00451bd6f5d082b4c860b

Thank you so much!

**Comment by emilyhuntsman** [comment]
Hi Teddy,
Please forgive me if I did something totally wrong, I'm pretty new to
github but am so excited to potentially have a way to help!
I created a dc.md using a friend's template and have modeled it after what
you did with la.md. Please let me know if that works! I'm getting friends
to send me emails they're written to their citycouncil people.
Emily
