### ISSUE TITLE
Please add Oakland CA!

### ISSUE THREAD

**Issue by snailsnacks12** [teddywilson/defund12.org#92]
Please add Oakland CA to the list. Thanks!

**Comment by cstrouse** [comment]
- Kimberly Jones, Chief of Staff (KJones3@Oaklandca.gov)
- Desmond Jeffress, Policy Director (DJeffress@oaklandca.gov)
- Ana Tellez, Community Liaison (AMTellez@oaklandca.gov)

# District 1

- Dan Kalb, District 1 (dkalb@oaklandca.gov)
- Deidra Moss, District 1 (dmoss@oaklandca.gov)

# District 2

- Nikki Fortunato Bas (nfbas@oaklandca.gov)
- Councilmember Bas: nfbas@oaklandca.gov
- Chief of Staff: mchen@oaklandca.gov
- Constituent Issues, Policy Analyst: lsalaverry@oaklandca.gov
- Communications/Media, Constituent Issues: tkang@oaklandca.gov
- Chinatown Liaison & Scheduler: nlin@oaklandca.gov
- Constituent Issues: pdrake@oaklandca.gov

# District 3

- Lynette Gibson McElhaney (LMcElhaney@oaklandca.gov)

# District 4

- Sheng Thao (district4@oaklandca.gov)

# District 5

- Noel Gallo (Ngallo@oaklandca.gov)

# District 6

- Loren Taylor (District6@oaklandca.gov)

# District 7

- Larry Reid (lreid@oaklandnet.com)

**Comment by starchy** [comment]
See also issue #10 and don't forget City Council President/Councilmember at Large Rebecca Kaplan, atlarge@oaklandca.gov.

**Comment by cjappl** [comment]
hey @snailsnacks12 , consider closing this. We are working on it over at #10, working on getting a statement together with APTP. I hope to have a PR for it by the end of the day!

Oakland solidarity!! :)

**Comment by serifluous** [comment]
Template proposed in issue #297
