### ISSUE TITLE
Please add Huntsville, AL

### ISSUE THREAD

**Issue by gghud** [teddywilson/defund12.org#94]
ELECTED OFFICIALS: 

City Council: 
Devyn S. Keith, President: Devyn.keith@HuntsvilleAL.gov
Frances Akridge: frances.akridge@huntsvilleAL.gov
Jennie Robinson: jennie.robinson@huntsvilleAL.gov
Bill Kling, Jr.: bill.kling@huntsvilleAL.gov
Will Culver: Will.culver@huntsvilleAL.gov 

Chairman of Madison County: 
Dale W. Strong: strongalabama@att.net

Board of Education 

Hi, my name is [NAME] and I am a resident of [NEIGHBORHOOD]. I am asking to redirect money away from the Huntsville PD and into the following social services: [LIST - Community Development, COVID Relief, Education, Parks & Recreation]. I request that an emergency meeting be called before the fiscal year goes into effect in order to deny the mayor's proposed budget and reallocate these funds to resources from which the citizens can benefit. 

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by cstrouse** [comment]
Closed via #124
