### ISSUE TITLE
Add Los Banos, CA please!

### ISSUE THREAD

**Issue by jewelgarcia86** [teddywilson/defund12.org#98]
Council Members of Los Banos:
mike.villalta@losbanos.org (Mayor)
tom.faria@losbanos.org
deborah.lewis@losbanos.org
daronica.johnson-santos@losbanos.org
brett.jones@losbanos.org

Thank you!!

**Comment by teddywilson** [comment]
Hey we will need a bit more information: 

- A subject message for the email
- A list of emails (at least one) for the government officials you’d like to receive the message
- A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

**Comment by jluvtokyo** [comment]
Following the city’s first BlackLivesMatter protest, the Leader of the protest was threatened by the mayor to keep things peaceful but after disagreeing with the mayor’s request he threatened to have the riot police called upon him and protestors! THIS IS UNACCEPTABLE for its the sole purpose of the protest in the first place! And for that our city’s police department deserves to be DEFUNDED!

mike.villalta@losbanos.org (Mayor)
tom.faria@losbanos.org
deborah.lewis@losbanos.org
daronica.johnson-santos@losbanos.org
brett.jones@losbanos.org
